mf_id = "letter_0820.json"
mf_lang = "en"
mf_label = "Kopie: Schwarzenbach, Annemarie an Schlumberger, Dominique; Korrespondenz"

[mf_data]
letter_0820_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0820_001.jpg/info.json"
letter_0820_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0820_002.jpg/info.json"
