mf_id = "letter_0746.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Maillart, Dagmar; Korrespondenz"

[mf_data]
letter_0746_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0746_001.jpg/info.json"
letter_0746_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0746_002.jpg/info.json"
