mf_id = "letter_0492.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Bodmer-Preiswerk, Marie-Louise; Korrespondenz"

[mf_data]
letter_0492_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0492_001.jpg/info.json"
letter_0492_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0492_002.jpg/info.json"
letter_0492_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0492_003.jpg/info.json"
letter_0492_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0492_004.jpg/info.json"
letter_0492_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0492_005.jpg/info.json"
