mf_id = "letter_0811.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Wolkenberg, Alfred; Korrespondenz"

[mf_data]
letter_0811_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0811_001.jpg/info.json"
letter_0811_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0811_002.jpg/info.json"
