mf_id = "letter_0509.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Bodmer-Preiswerk, Marie-Louise; Korrespondenz"

[mf_data]
letter_0509_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0509_001.jpg/info.json"
letter_0509_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0509_002.jpg/info.json"
letter_0509_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0509_003.jpg/info.json"
