mf_id = "letter_0721.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Maillart, Ella; Korrespondenz"

[mf_data]
letter_0721_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0721_001.jpg/info.json"
letter_0721_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0721_002.jpg/info.json"
