mf_id = "letter_0729.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Maillart, Ella; Korrespondenz"

[mf_data]
letter_0729_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0729_001.jpg/info.json"
letter_0729_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0729_002.jpg/info.json"
letter_0729_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0729_003.jpg/info.json"
letter_0729_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0729_004.jpg/info.json"
letter_0729_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0729_005.jpg/info.json"
letter_0729_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0729_006.jpg/info.json"
