mf_id = "letter_0905.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Nougarède, Jaqueline"

[mf_data]
letter_0905_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0905_001.jpg/info.json"
letter_0905_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0905_002.jpg/info.json"
