mf_id = "letter_0844.json"
mf_lang = "en"
mf_label = "Kopie: Schwarzenbach, Annemarie an Schlumberger, Dominique; Korrespondenz"

[mf_data]
letter_0844_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0844_001.jpg/info.json"
letter_0844_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0844_002.jpg/info.json"
