mf_id = "letter_0891.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Nougarède, Jaqueline"

[mf_data]
letter_0891_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0891_001.jpg/info.json"
letter_0891_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0891_002.jpg/info.json"
letter_0891_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0891_003.jpg/info.json"
