mf_id = "letter_0607.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0607_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0607_001.jpg/info.json"
letter_0607_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0607_002.jpg/info.json"
letter_0607_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0607_003.jpg/info.json"
letter_0607_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0607_004.jpg/info.json"
letter_0607_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0607_005.jpg/info.json"
letter_0607_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0607_006.jpg/info.json"
letter_0607_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0607_007.jpg/info.json"
letter_0607_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0607_008.jpg/info.json"
