mf_id = "letter_0601.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0601_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0601_001.jpg/info.json"
