mf_id = "letter_0547.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Bodmer-Preiswerk, Marie-Louise; Korrespondenz"

[mf_data]
letter_0547_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0547_001.jpg/info.json"
letter_0547_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0547_002.jpg/info.json"
letter_0547_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0547_003.jpg/info.json"
letter_0547_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0547_004.jpg/info.json"
letter_0547_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0547_005.jpg/info.json"
letter_0547_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0547_006.jpg/info.json"
