mf_id = "letter_0779.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Merz, Ernst; Korrespondenz"

[mf_data]
letter_0779_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0779_001.jpg/info.json"
letter_0779_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0779_002.jpg/info.json"
letter_0779_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0779_003.jpg/info.json"
