mf_id = "letter_0702.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Haushofer, Albrecht; Korrespondenz"

[mf_data]
letter_0702_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0702_001.jpg/info.json"
letter_0702_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0702_002.jpg/info.json"
letter_0702_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0702_003.jpg/info.json"
letter_0702_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0702_004.jpg/info.json"
