mf_id = "letter_0663.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0663_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0663_001.jpg/info.json"
letter_0663_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0663_002.jpg/info.json"
letter_0663_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0663_003.jpg/info.json"
letter_0663_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0663_004.jpg/info.json"
