mf_id = "letter_0585.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0585_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0585_001.jpg/info.json"
letter_0585_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0585_002.jpg/info.json"
letter_0585_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0585_003.jpg/info.json"
letter_0585_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0585_004.jpg/info.json"
letter_0585_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0585_005.jpg/info.json"
letter_0585_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0585_006.jpg/info.json"
letter_0585_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0585_007.jpg/info.json"
