mf_id = "letter_0804.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Wolkenberg, Alfred; Korrespondenz"

[mf_data]
letter_0804_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0804_001.jpg/info.json"
letter_0804_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0804_002.jpg/info.json"
letter_0804_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0804_003.jpg/info.json"
letter_0804_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0804_004.jpg/info.json"
