mf_id = "letter_0783.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Merz, Ernst; Korrespondenz"

[mf_data]
letter_0783_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0783_001.jpg/info.json"
letter_0783_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0783_002.jpg/info.json"
