mf_id = "letter_0845.json"
mf_lang = "en"
mf_label = "Kopie: Schwarzenbach, Annemarie an Schlumberger, Dominique; Korrespondenz"

[mf_data]
letter_0845_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0845_001.jpg/info.json"
letter_0845_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0845_002.jpg/info.json"
letter_0845_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0845_003.jpg/info.json"
