mf_id = "letter_0638.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0638_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0638_001.jpg/info.json"
letter_0638_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0638_002.jpg/info.json"
