mf_id = "letter_0824.json"
mf_lang = "en"
mf_label = "Kopie: Schwarzenbach, Annemarie an Schlumberger, Dominique; Korrespondenz"

[mf_data]
letter_0824_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0824_001.jpg/info.json"
