mf_id = "letter_0790.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Wolkenberg, Alfred; Korrespondenz"

[mf_data]
letter_0790_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0790_001.jpg/info.json"
