mf_id = "letter_0784.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an N. N.; Korrespondenz"

[mf_data]
letter_0784_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0784_001.jpg/info.json"
