mf_id = "letter_0751.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Maillart, Dagmar; Korrespondenz"

[mf_data]
letter_0751_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0751_001.jpg/info.json"
letter_0751_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0751_002.jpg/info.json"
