mf_id = "letter_0602.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0602_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0602_001.jpg/info.json"
letter_0602_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0602_002.jpg/info.json"
letter_0602_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0602_003.jpg/info.json"
letter_0602_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0602_004.jpg/info.json"
