mf_id = "letter_0887.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Nougarède, Jaqueline"

[mf_data]
letter_0887_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0887_001.jpg/info.json"
letter_0887_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0887_002.jpg/info.json"
letter_0887_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0887_003.jpg/info.json"
letter_0887_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0887_004.jpg/info.json"
letter_0887_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0887_005.jpg/info.json"
