mf_id = "letter_0664.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0664_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0664_001.jpg/info.json"
letter_0664_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0664_002.jpg/info.json"
letter_0664_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0664_003.jpg/info.json"
letter_0664_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0664_004.jpg/info.json"
letter_0664_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0664_005.jpg/info.json"
letter_0664_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0664_006.jpg/info.json"
letter_0664_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0664_007.jpg/info.json"
letter_0664_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0664_008.jpg/info.json"
