mf_id = "letter_0788.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Schwarzenbach, Renée; Korrespondenz"

[mf_data]
letter_0788_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0788_001.jpg/info.json"
