mf_id = "longform_0024.json"
mf_lang = "en"
mf_label = "Beim Verlassen Afrikas / Afrikanische Wirklichkeit [Textzeuge c]"

[mf_data]
longform_0024_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0001.jpg/info.json"
longform_0024_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0002.jpg/info.json"
longform_0024_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0003.jpg/info.json"
longform_0024_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0004.jpg/info.json"
longform_0024_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0005.jpg/info.json"
longform_0024_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0006.jpg/info.json"
longform_0024_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0007.jpg/info.json"
longform_0024_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0008.jpg/info.json"
longform_0024_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0009.jpg/info.json"
longform_0024_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0010.jpg/info.json"
longform_0024_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0011.jpg/info.json"
longform_0024_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0012.jpg/info.json"
longform_0024_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0013.jpg/info.json"
longform_0024_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0014.jpg/info.json"
longform_0024_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0015.jpg/info.json"
longform_0024_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0016.jpg/info.json"
longform_0024_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0017.jpg/info.json"
longform_0024_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0018.jpg/info.json"
longform_0024_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0019.jpg/info.json"
longform_0024_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0020.jpg/info.json"
longform_0024_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0021.jpg/info.json"
longform_0024_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0022.jpg/info.json"
longform_0024_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0023.jpg/info.json"
longform_0024_024 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0024.jpg/info.json"
longform_0024_025 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0025.jpg/info.json"
longform_0024_026 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0026.jpg/info.json"
longform_0024_027 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0027.jpg/info.json"
longform_0024_028 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0028.jpg/info.json"
longform_0024_029 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0029.jpg/info.json"
longform_0024_030 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0030.jpg/info.json"
longform_0024_031 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0031.jpg/info.json"
longform_0024_032 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0032.jpg/info.json"
longform_0024_033 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0033.jpg/info.json"
longform_0024_034 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0034.jpg/info.json"
longform_0024_035 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0035.jpg/info.json"
longform_0024_036 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0036.jpg/info.json"
longform_0024_037 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0037.jpg/info.json"
longform_0024_038 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0038.jpg/info.json"
longform_0024_039 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0039.jpg/info.json"
longform_0024_040 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0040.jpg/info.json"
longform_0024_041 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0041.jpg/info.json"
longform_0024_042 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0042.jpg/info.json"
longform_0024_043 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0043.jpg/info.json"
longform_0024_044 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0044.jpg/info.json"
longform_0024_045 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0045.jpg/info.json"
longform_0024_046 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0046.jpg/info.json"
longform_0024_047 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0047.jpg/info.json"
longform_0024_048 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0048.jpg/info.json"
longform_0024_049 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0049.jpg/info.json"
longform_0024_050 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0050.jpg/info.json"
longform_0024_051 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0051.jpg/info.json"
longform_0024_052 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0052.jpg/info.json"
longform_0024_053 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0053.jpg/info.json"
longform_0024_054 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0054.jpg/info.json"
longform_0024_055 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0055.jpg/info.json"
longform_0024_056 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0056.jpg/info.json"
longform_0024_057 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0057.jpg/info.json"
longform_0024_058 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0058.jpg/info.json"
longform_0024_059 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0059.jpg/info.json"
longform_0024_060 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0060.jpg/info.json"
longform_0024_061 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0061.jpg/info.json"
longform_0024_062 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0062.jpg/info.json"
longform_0024_063 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0063.jpg/info.json"
longform_0024_064 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0064.jpg/info.json"
longform_0024_065 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0065.jpg/info.json"
longform_0024_066 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0066.jpg/info.json"
longform_0024_067 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0024_0067.jpg/info.json"
