mf_id = "longform_0023.json"
mf_lang = "en"
mf_label = "[Das Wunder des Baums] II [Textzeuge c]"

[mf_data]
longform_0023_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0001.jpg/info.json"
longform_0023_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0002.jpg/info.json"
longform_0023_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0003.jpg/info.json"
longform_0023_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0004.jpg/info.json"
longform_0023_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0005.jpg/info.json"
longform_0023_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0006.jpg/info.json"
longform_0023_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0007.jpg/info.json"
longform_0023_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0008.jpg/info.json"
longform_0023_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0009.jpg/info.json"
longform_0023_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0010.jpg/info.json"
longform_0023_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0011.jpg/info.json"
longform_0023_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0012.jpg/info.json"
longform_0023_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0013.jpg/info.json"
longform_0023_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0014.jpg/info.json"
longform_0023_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0015.jpg/info.json"
longform_0023_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0016.jpg/info.json"
longform_0023_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0017.jpg/info.json"
longform_0023_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0018.jpg/info.json"
longform_0023_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0019.jpg/info.json"
longform_0023_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0020.jpg/info.json"
longform_0023_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0021.jpg/info.json"
longform_0023_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0022.jpg/info.json"
longform_0023_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0023.jpg/info.json"
longform_0023_024 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0024.jpg/info.json"
longform_0023_025 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0025.jpg/info.json"
longform_0023_026 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0026.jpg/info.json"
longform_0023_027 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0027.jpg/info.json"
longform_0023_028 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0028.jpg/info.json"
longform_0023_029 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0029.jpg/info.json"
longform_0023_030 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0030.jpg/info.json"
longform_0023_031 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0031.jpg/info.json"
longform_0023_032 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0032.jpg/info.json"
longform_0023_033 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0033.jpg/info.json"
longform_0023_034 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0034.jpg/info.json"
longform_0023_035 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0035.jpg/info.json"
longform_0023_036 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0036.jpg/info.json"
longform_0023_037 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0037.jpg/info.json"
longform_0023_038 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0038.jpg/info.json"
longform_0023_039 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0039.jpg/info.json"
longform_0023_040 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0040.jpg/info.json"
longform_0023_041 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0041.jpg/info.json"
longform_0023_042 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0042.jpg/info.json"
longform_0023_043 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0043.jpg/info.json"
longform_0023_044 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0044.jpg/info.json"
longform_0023_045 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0045.jpg/info.json"
longform_0023_046 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0046.jpg/info.json"
longform_0023_047 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0047.jpg/info.json"
longform_0023_048 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0048.jpg/info.json"
longform_0023_049 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0049.jpg/info.json"
longform_0023_050 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0050.jpg/info.json"
longform_0023_051 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0051.jpg/info.json"
longform_0023_052 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0052.jpg/info.json"
longform_0023_053 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0053.jpg/info.json"
longform_0023_054 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0054.jpg/info.json"
longform_0023_055 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0055.jpg/info.json"
longform_0023_056 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0056.jpg/info.json"
longform_0023_057 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0057.jpg/info.json"
longform_0023_058 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0058.jpg/info.json"
longform_0023_059 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0059.jpg/info.json"
longform_0023_060 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0060.jpg/info.json"
longform_0023_061 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0061.jpg/info.json"
longform_0023_062 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0062.jpg/info.json"
longform_0023_063 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0063.jpg/info.json"
longform_0023_064 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0064.jpg/info.json"
longform_0023_065 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0065.jpg/info.json"
longform_0023_066 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0066.jpg/info.json"
longform_0023_067 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0067.jpg/info.json"
longform_0023_068 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0068.jpg/info.json"
longform_0023_069 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0069.jpg/info.json"
longform_0023_070 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0070.jpg/info.json"
longform_0023_071 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0071.jpg/info.json"
longform_0023_072 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0072.jpg/info.json"
longform_0023_073 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0073.jpg/info.json"
longform_0023_074 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0074.jpg/info.json"
longform_0023_075 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0075.jpg/info.json"
longform_0023_076 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0076.jpg/info.json"
longform_0023_077 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0077.jpg/info.json"
longform_0023_078 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0078.jpg/info.json"
longform_0023_079 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0079.jpg/info.json"
longform_0023_080 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0080.jpg/info.json"
longform_0023_081 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0081.jpg/info.json"
longform_0023_082 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0082.jpg/info.json"
longform_0023_083 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0083.jpg/info.json"
longform_0023_084 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0084.jpg/info.json"
longform_0023_085 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0085.jpg/info.json"
longform_0023_086 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0086.jpg/info.json"
longform_0023_087 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0087.jpg/info.json"
longform_0023_088 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0088.jpg/info.json"
longform_0023_089 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0089.jpg/info.json"
longform_0023_090 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0090.jpg/info.json"
longform_0023_091 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0091.jpg/info.json"
longform_0023_092 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0092.jpg/info.json"
longform_0023_093 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0093.jpg/info.json"
longform_0023_094 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0094.jpg/info.json"
longform_0023_095 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0095.jpg/info.json"
longform_0023_096 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0096.jpg/info.json"
longform_0023_097 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0097.jpg/info.json"
longform_0023_098 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0098.jpg/info.json"
longform_0023_099 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0099.jpg/info.json"
longform_0023_100 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0100.jpg/info.json"
longform_0023_101 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0101.jpg/info.json"
longform_0023_102 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0102.jpg/info.json"
longform_0023_103 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0103.jpg/info.json"
longform_0023_104 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0104.jpg/info.json"
longform_0023_105 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0105.jpg/info.json"
longform_0023_106 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0106.jpg/info.json"
longform_0023_107 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0107.jpg/info.json"
longform_0023_108 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0108.jpg/info.json"
longform_0023_109 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0109.jpg/info.json"
longform_0023_110 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0110.jpg/info.json"
longform_0023_111 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0111.jpg/info.json"
longform_0023_112 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0112.jpg/info.json"
longform_0023_113 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0113.jpg/info.json"
longform_0023_114 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0114.jpg/info.json"
longform_0023_115 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0115.jpg/info.json"
longform_0023_116 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0116.jpg/info.json"
longform_0023_117 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0117.jpg/info.json"
longform_0023_118 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0118.jpg/info.json"
longform_0023_119 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0119.jpg/info.json"
longform_0023_120 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0120.jpg/info.json"
longform_0023_121 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0121.jpg/info.json"
longform_0023_122 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0122.jpg/info.json"
longform_0023_123 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0123.jpg/info.json"
longform_0023_124 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0124.jpg/info.json"
longform_0023_125 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0125.jpg/info.json"
