mf_id = "longform_0022.json"
mf_lang = "en"
mf_label = "[Das Wunder des Baums] I [Textzeuge b]"

[mf_data]
"longform_0022_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0001.jpg/info.json"
"longform_0022_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0002.jpg/info.json"
"longform_0022_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0003.jpg/info.json"
"longform_0022_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0004.jpg/info.json"
"longform_0022_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0005.jpg/info.json"
"longform_0022_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0006.jpg/info.json"
"longform_0022_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0007.jpg/info.json"
"longform_0022_0008.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0008.jpg/info.json"
"longform_0022_0009.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0009.jpg/info.json"
"longform_0022_0010.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0010.jpg/info.json"
"longform_0022_0011.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0011.jpg/info.json"
"longform_0022_0012.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0012.jpg/info.json"
"longform_0022_0013.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0013.jpg/info.json"
"longform_0022_0014.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0014.jpg/info.json"
"longform_0022_0015.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0015.jpg/info.json"
"longform_0022_0016.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0016.jpg/info.json"
"longform_0022_0017.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0017.jpg/info.json"
"longform_0022_0018.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0018.jpg/info.json"
"longform_0022_0019.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0019.jpg/info.json"
"longform_0022_0020.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0020.jpg/info.json"
"longform_0022_0021.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0021.jpg/info.json"
"longform_0022_0022.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0022.jpg/info.json"
"longform_0022_0023.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0023.jpg/info.json"
"longform_0022_0024.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0024.jpg/info.json"
"longform_0022_0025.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0025.jpg/info.json"
"longform_0022_0026.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0026.jpg/info.json"
"longform_0022_0027.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0027.jpg/info.json"
"longform_0022_0028.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0028.jpg/info.json"
"longform_0022_0029.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0029.jpg/info.json"
"longform_0022_0030.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0030.jpg/info.json"
"longform_0022_0031.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0031.jpg/info.json"
"longform_0022_0032.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0032.jpg/info.json"
"longform_0022_0033.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0033.jpg/info.json"
"longform_0022_0034.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0034.jpg/info.json"
"longform_0022_0035.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0035.jpg/info.json"
"longform_0022_0036.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0036.jpg/info.json"
"longform_0022_0037.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0037.jpg/info.json"
"longform_0022_0038.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0038.jpg/info.json"
"longform_0022_0039.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0039.jpg/info.json"
"longform_0022_0040.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0040.jpg/info.json"
"longform_0022_0041.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0041.jpg/info.json"
"longform_0022_0042.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0042.jpg/info.json"
"longform_0022_0043.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0043.jpg/info.json"
"longform_0022_0044.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0044.jpg/info.json"
"longform_0022_0045.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0045.jpg/info.json"
"longform_0022_0046.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0046.jpg/info.json"
"longform_0022_0047.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0047.jpg/info.json"
"longform_0022_0048.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0048.jpg/info.json"
"longform_0022_0049.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0049.jpg/info.json"
"longform_0022_0050.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0050.jpg/info.json"
"longform_0022_0051.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0051.jpg/info.json"
"longform_0022_0052.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0052.jpg/info.json"
"longform_0022_0053.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0053.jpg/info.json"
"longform_0022_0054.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0054.jpg/info.json"
"longform_0022_0055.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0055.jpg/info.json"
"longform_0022_0056.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0056.jpg/info.json"
"longform_0022_0057.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0057.jpg/info.json"
"longform_0022_0058.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0058.jpg/info.json"
"longform_0022_0059.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0059.jpg/info.json"
"longform_0022_0060.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0060.jpg/info.json"
"longform_0022_0061.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0061.jpg/info.json"
"longform_0022_0062.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0062.jpg/info.json"
"longform_0022_0063.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0063.jpg/info.json"
"longform_0022_0064.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0064.jpg/info.json"
"longform_0022_0065.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0022_0065.jpg/info.json"
