mf_id = "longform_0019.json"
mf_lang = "en"
mf_label = "Marc [Textzeuge b]"

[mf_data]
longform_0019_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0001.jpg/info.json"
longform_0019_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0002.jpg/info.json"
longform_0019_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0003.jpg/info.json"
longform_0019_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0004.jpg/info.json"
longform_0019_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0005.jpg/info.json"
longform_0019_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0006.jpg/info.json"
longform_0019_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0007.jpg/info.json"
longform_0019_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0008.jpg/info.json"
longform_0019_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0009.jpg/info.json"
longform_0019_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0010.jpg/info.json"
longform_0019_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0011.jpg/info.json"
longform_0019_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0012.jpg/info.json"
longform_0019_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0013.jpg/info.json"
longform_0019_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0014.jpg/info.json"
longform_0019_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0015.jpg/info.json"
longform_0019_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0016.jpg/info.json"
longform_0019_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0017.jpg/info.json"
longform_0019_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0018.jpg/info.json"
longform_0019_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0019.jpg/info.json"
longform_0019_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0020.jpg/info.json"
longform_0019_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0021.jpg/info.json"
longform_0019_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0022.jpg/info.json"
longform_0019_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0023.jpg/info.json"
longform_0019_024 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0024.jpg/info.json"
longform_0019_025 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0025.jpg/info.json"
longform_0019_026 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0026.jpg/info.json"
longform_0019_027 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0027.jpg/info.json"
longform_0019_028 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0028.jpg/info.json"
longform_0019_029 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0029.jpg/info.json"
longform_0019_030 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0030.jpg/info.json"
longform_0019_031 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0031.jpg/info.json"
longform_0019_032 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0032.jpg/info.json"
longform_0019_033 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0033.jpg/info.json"
longform_0019_034 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0034.jpg/info.json"
longform_0019_035 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0035.jpg/info.json"
longform_0019_036 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0036.jpg/info.json"
longform_0019_037 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0037.jpg/info.json"
longform_0019_038 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0038.jpg/info.json"
longform_0019_039 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0039.jpg/info.json"
longform_0019_040 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0040.jpg/info.json"
longform_0019_041 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0041.jpg/info.json"
longform_0019_042 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0042.jpg/info.json"
longform_0019_043 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0043.jpg/info.json"
longform_0019_044 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0044.jpg/info.json"
longform_0019_045 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0045.jpg/info.json"
longform_0019_046 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0046.jpg/info.json"
longform_0019_047 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0047.jpg/info.json"
longform_0019_048 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0048.jpg/info.json"
longform_0019_049 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0049.jpg/info.json"
longform_0019_050 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0050.jpg/info.json"
longform_0019_051 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0051.jpg/info.json"
longform_0019_052 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0052.jpg/info.json"
longform_0019_053 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0053.jpg/info.json"
longform_0019_054 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0054.jpg/info.json"
longform_0019_055 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0055.jpg/info.json"
longform_0019_056 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0056.jpg/info.json"
longform_0019_057 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0057.jpg/info.json"
longform_0019_058 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0058.jpg/info.json"
longform_0019_059 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0059.jpg/info.json"
longform_0019_060 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0060.jpg/info.json"
longform_0019_061 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0061.jpg/info.json"
longform_0019_062 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0062.jpg/info.json"
longform_0019_063 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0063.jpg/info.json"
longform_0019_064 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0064.jpg/info.json"
longform_0019_065 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0019_0065.jpg/info.json"
