mf_id = "smallform_0734.json"
mf_lang = "en"
mf_label = "Eine Stunde vor Funchal"

[mf_data]
"smallform_0734_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0734_0001.jpg/info.json"
"smallform_0734_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0734_0002.jpg/info.json"
"smallform_0734_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0734_0003.jpg/info.json"
"smallform_0734_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0734_0004.jpg/info.json"
