mf_id = "smallform_0324.json"
mf_lang = "en"
mf_label = "Dreimal der Hindukusch"

[mf_data]
smallform_0324_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0324_0001.jpg/info.json"
smallform_0324_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0324_0002.jpg/info.json"
smallform_0324_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0324_0003.jpg/info.json"
smallform_0324_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0324_0004.jpg/info.json"
smallform_0324_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0324_0005.jpg/info.json"
