mf_id = "smallform_0379.json"
mf_lang = "en"
mf_label = "*Aktuelles aus Afghanistan [Textzeuge a]"

[mf_data]
smallform_0379_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0379_0001.jpg/info.json"
smallform_0379_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0379_0002.jpg/info.json"
smallform_0379_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0379_0003.jpg/info.json"
