mf_id = "smallform_0735.json"
mf_lang = "en"
mf_label = "Eine Mondnacht in der Chella"

[mf_data]
"smallform_0735_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0735_0001.jpg/info.json"
"smallform_0735_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0735_0002.jpg/info.json"
"smallform_0735_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0735_0003.jpg/info.json"
"smallform_0735_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0735_0004.jpg/info.json"
"smallform_0735_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0735_0005.jpg/info.json"
