mf_id = "smallform_0293.json"
mf_lang = "en"
mf_label = "Unfreiwilliger Streik der Prager Korrespondenten (27.9.1938)"

[mf_data]
smallform_0293_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0293_0001.jpg/info.json"
smallform_0293_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0293_0002.jpg/info.json"
smallform_0293_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0293_0003.jpg/info.json"
smallform_0293_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0293_0004.jpg/info.json"
smallform_0293_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0293_0005.jpg/info.json"
