mf_id = "smallform_0433.json"
mf_lang = "en"
mf_label = " Die Reise durch den Suez-Kanal"

[mf_data]
"smallform_0433_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0433_0001.jpg/info.json"
"smallform_0433_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0433_0002.jpg/info.json"
"smallform_0433_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0433_0003.jpg/info.json"
