mf_id = "smallform_0316.json"
mf_lang = "en"
mf_label = "Quer durch Klein-Asien : eine Strasse im Bau (2) [Textzeuge a]"

[mf_data]
smallform_0316_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0316_0001.jpg/info.json"
smallform_0316_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0316_0002.jpg/info.json"
smallform_0316_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0316_0003.jpg/info.json"
