mf_id = "smallform_0108.json"
mf_lang = "en"
mf_label = "Das Tal Dargawskaja"

[mf_data]
smallform_0108_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0108_0001.jpg/info.json"
smallform_0108_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0108_0002.jpg/info.json"
smallform_0108_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0108_0003.jpg/info.json"
smallform_0108_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0108_0004.jpg/info.json"
smallform_0108_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0108_0005.jpg/info.json"
smallform_0108_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0108_0006.jpg/info.json"
