mf_id = "smallform_0046.json"
mf_lang = "en"
mf_label = "Istanbul (Aufzeichnungen)"

[mf_data]
smallform_0046_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0046_0001.jpg/info.json"
smallform_0046_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0046_0002.jpg/info.json"
smallform_0046_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0046_0003.jpg/info.json"
