mf_id = "smallform_0092.json"
mf_lang = "en"
mf_label = "Luristan-Bronzen und Keramik aus Nehawend"

[mf_data]
"smallform_0092_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0092_0001.jpg/info.json"
"smallform_0092_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0092_0002.jpg/info.json"
"smallform_0092_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0092_0003.jpg/info.json"
"smallform_0092_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0092_0004.jpg/info.json"
"smallform_0092_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0092_0005.jpg/info.json"
"smallform_0092_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0092_0006.jpg/info.json"
