mf_id = "smallform_0517.json"
mf_lang = "en"
mf_label = "Am Äquator / Äquatornähe [Textzeuge a]"

[mf_data]
"smallform_0517_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0517_0001.jpg/info.json"
"smallform_0517_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0517_0002.jpg/info.json"
"smallform_0517_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0517_0003.jpg/info.json"
"smallform_0517_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0517_0004.jpg/info.json"
"smallform_0517_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0517_0005.jpg/info.json"
