mf_id = "smallform_0418.json"
mf_lang = "en"
mf_label = "[Iran-Afghanistan- Britisch Indien]"

[mf_data]
smallform_0418_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0418_0001.jpg/info.json"
