mf_id = "smallform_0215.json"
mf_lang = "en"
mf_label = "Baltisches Tagebuch"

[mf_data]
smallform_0215_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0001.jpg/info.json"
smallform_0215_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0002.jpg/info.json"
smallform_0215_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0003.jpg/info.json"
smallform_0215_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0004.jpg/info.json"
smallform_0215_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0005.jpg/info.json"
smallform_0215_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0006.jpg/info.json"
smallform_0215_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0007.jpg/info.json"
smallform_0215_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0008.jpg/info.json"
smallform_0215_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0009.jpg/info.json"
smallform_0215_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0010.jpg/info.json"
smallform_0215_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0011.jpg/info.json"
smallform_0215_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0012.jpg/info.json"
smallform_0215_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0013.jpg/info.json"
smallform_0215_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0014.jpg/info.json"
smallform_0215_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0015.jpg/info.json"
smallform_0215_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0016.jpg/info.json"
smallform_0215_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0017.jpg/info.json"
smallform_0215_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0018.jpg/info.json"
smallform_0215_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0215_0019.jpg/info.json"
