mf_id = "smallform_0116.json"
mf_lang = "en"
mf_label = "Polo und persische Ringer"

[mf_data]
smallform_0116_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0116_0001.jpg/info.json"
smallform_0116_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0116_0002.jpg/info.json"
smallform_0116_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0116_0003.jpg/info.json"
smallform_0116_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0116_0004.jpg/info.json"
smallform_0116_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0116_0005.jpg/info.json"
smallform_0116_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0116_0006.jpg/info.json"
