mf_id = "smallform_0445.json"
mf_lang = "en"
mf_label = "Amerikanisches Tagebuch. II. Von New York nach Washington [Textzeuge a]"

[mf_data]
smallform_0445_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0445_0001.jpg/info.json"
smallform_0445_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0445_0002.jpg/info.json"
smallform_0445_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0445_0003.jpg/info.json"
smallform_0445_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0445_0004.jpg/info.json"
