mf_id = "smallform_0357.json"
mf_lang = "en"
mf_label = "Schwarze Zelte in Afghanistan"

[mf_data]
"smallform_0357_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0357_0001.jpg/info.json"
"smallform_0357_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0357_0002.jpg/info.json"
"smallform_0357_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0357_0003.jpg/info.json"
"smallform_0357_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0357_0004.jpg/info.json"
"smallform_0357_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0357_0005.jpg/info.json"
"smallform_0357_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0357_0006.jpg/info.json"
