mf_id = "smallform_0237.json"
mf_lang = "en"
mf_label = "Die Eroberung des Khan Tengri - ein tragischer Sieg : Bildbericht über die letzte Expedition Lorenz Saladins"

[mf_data]
smallform_0237_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0237_0001.jpg/info.json"
smallform_0237_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0237_0002.jpg/info.json"
smallform_0237_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0237_0003.jpg/info.json"
