mf_id = "smallform_0328.json"
mf_lang = "en"
mf_label = "Die Töpfer von Istalif [Textzeuge a]"

[mf_data]
smallform_0328_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0328_0001.jpg/info.json"
smallform_0328_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0328_0002.jpg/info.json"
smallform_0328_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0328_0003.jpg/info.json"
