mf_id = "smallform_0339.json"
mf_lang = "en"
mf_label = "Iran und Afghanistan, zwei Grenzen der Weltpolitik"

[mf_data]
smallform_0339_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0339_0001.jpg/info.json"
smallform_0339_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0339_0002.jpg/info.json"
smallform_0339_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0339_0003.jpg/info.json"
