mf_id = "smallform_0655.json"
mf_lang = "en"
mf_label = "Baalbek : Geschichte einer Entdeckung [Textzeuge b]"

[mf_data]
smallform_0655_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0655_0001.jpg/info.json"
smallform_0655_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0655_0002.jpg/info.json"
smallform_0655_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0655_0003.jpg/info.json"
smallform_0655_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0655_0004.jpg/info.json"
smallform_0655_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0655_0005.jpg/info.json"
smallform_0655_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0655_0006.jpg/info.json"
smallform_0655_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0655_0007.jpg/info.json"
