mf_id = "smallform_0144.json"
mf_lang = "en"
mf_label = "Eine Frau allein "

[mf_data]
"smallform_0144_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0001.jpg/info.json"
"smallform_0144_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0002.jpg/info.json"
"smallform_0144_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0003.jpg/info.json"
"smallform_0144_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0004.jpg/info.json"
"smallform_0144_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0005.jpg/info.json"
"smallform_0144_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0006.jpg/info.json"
"smallform_0144_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0007.jpg/info.json"
"smallform_0144_0008.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0008.jpg/info.json"
"smallform_0144_0009.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0009.jpg/info.json"
"smallform_0144_0010.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0010.jpg/info.json"
"smallform_0144_0011.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0011.jpg/info.json"
"smallform_0144_0012.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0012.jpg/info.json"
"smallform_0144_0013.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0013.jpg/info.json"
"smallform_0144_0014.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0014.jpg/info.json"
"smallform_0144_0015.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0015.jpg/info.json"
"smallform_0144_0016.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0016.jpg/info.json"
"smallform_0144_0017.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0017.jpg/info.json"
"smallform_0144_0018.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0018.jpg/info.json"
"smallform_0144_0019.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0019.jpg/info.json"
"smallform_0144_0020.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0020.jpg/info.json"
"smallform_0144_0021.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0021.jpg/info.json"
"smallform_0144_0022.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0022.jpg/info.json"
"smallform_0144_0023.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0023.jpg/info.json"
"smallform_0144_0024.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0024.jpg/info.json"
"smallform_0144_0025.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0025.jpg/info.json"
"smallform_0144_0026.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0026.jpg/info.json"
"smallform_0144_0027.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0027.jpg/info.json"
"smallform_0144_0028.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0028.jpg/info.json"
"smallform_0144_0029.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0144_0029.jpg/info.json"
