mf_id = "smallform_0117.json"
mf_lang = "en"
mf_label = "Regen in Tiflis"

[mf_data]
smallform_0117_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0117_0001.jpg/info.json"
smallform_0117_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0117_0002.jpg/info.json"
smallform_0117_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0117_0003.jpg/info.json"
smallform_0117_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0117_0004.jpg/info.json"
smallform_0117_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0117_0005.jpg/info.json"
