mf_id = "smallform_0459.json"
mf_lang = "en"
mf_label = "Jahreswechsel in U.S.A.: 1. Der Maginot-Ozean; 2. Missa Solemnis; 3. Januar-Sensationen; 4. Die weissen Ebenen"

[mf_data]
smallform_0459_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0001.jpg/info.json"
smallform_0459_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0002.jpg/info.json"
smallform_0459_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0003.jpg/info.json"
smallform_0459_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0004.jpg/info.json"
smallform_0459_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0005.jpg/info.json"
smallform_0459_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0006.jpg/info.json"
smallform_0459_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0007.jpg/info.json"
smallform_0459_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0008.jpg/info.json"
smallform_0459_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0009.jpg/info.json"
smallform_0459_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0010.jpg/info.json"
smallform_0459_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0011.jpg/info.json"
smallform_0459_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0012.jpg/info.json"
smallform_0459_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0013.jpg/info.json"
smallform_0459_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0014.jpg/info.json"
smallform_0459_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0015.jpg/info.json"
smallform_0459_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0016.jpg/info.json"
smallform_0459_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0017.jpg/info.json"
smallform_0459_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0018.jpg/info.json"
smallform_0459_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0019.jpg/info.json"
smallform_0459_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0020.jpg/info.json"
smallform_0459_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0459_0021.jpg/info.json"
