mf_id = "smallform_0701.json"
mf_lang = "en"
mf_label = "Herr! Das Namenlose (März/ April 1941) [Textzeuge c]"

[mf_data]
smallform_0701_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0701_0001.jpg/info.json"
smallform_0701_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0701_0002.jpg/info.json"
smallform_0701_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0701_0003.jpg/info.json"
smallform_0701_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0701_0004.jpg/info.json"
smallform_0701_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0701_0005.jpg/info.json"
smallform_0701_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0701_0006.jpg/info.json"
smallform_0701_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0701_0007.jpg/info.json"
smallform_0701_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0701_0008.jpg/info.json"
