mf_id = "smallform_0136.json"
mf_lang = "en"
mf_label = "Das gelobte Land"

[mf_data]
smallform_0136_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0001.jpg/info.json"
smallform_0136_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0002.jpg/info.json"
smallform_0136_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0003.jpg/info.json"
smallform_0136_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0004.jpg/info.json"
smallform_0136_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0005.jpg/info.json"
smallform_0136_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0006.jpg/info.json"
smallform_0136_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0007.jpg/info.json"
smallform_0136_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0008.jpg/info.json"
smallform_0136_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0009.jpg/info.json"
smallform_0136_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0010.jpg/info.json"
smallform_0136_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0011.jpg/info.json"
smallform_0136_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0012.jpg/info.json"
smallform_0136_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0013.jpg/info.json"
smallform_0136_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0014.jpg/info.json"
smallform_0136_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0015.jpg/info.json"
smallform_0136_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0136_0016.jpg/info.json"
