mf_id = "smallform_0767.json"
mf_lang = "en"
mf_label = "6. Lob des Gesangs im Freien [Textzeuge c - Fotokopie]"

[mf_data]
"smallform_0767_0016.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0767_0016.jpg/info.json"
"smallform_0767_0017.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0767_0017.jpg/info.json"
"smallform_0767_0018.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0767_0018.jpg/info.json"
