mf_id = "smallform_0656.json"
mf_lang = "en"
mf_label = "Ein Volksfest der Mohammedaner [Textzeuge b]"

[mf_data]
smallform_0656_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0656_0001.jpg/info.json"
smallform_0656_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0656_0002.jpg/info.json"
smallform_0656_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0656_0003.jpg/info.json"
smallform_0656_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0656_0004.jpg/info.json"
smallform_0656_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0656_0005.jpg/info.json"
smallform_0656_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0656_0006.jpg/info.json"
