mf_id = "smallform_0559.json"
mf_lang = "en"
mf_label = "Maroc. Bibliographie"

[mf_data]
smallform_0559_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0559_0001.jpg/info.json"
