mf_id = "smallform_0548.json"
mf_lang = "en"
mf_label = "Das Beispiel der weiblichen Jugend in Portugal"

[mf_data]
"smallform_0548_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0548_0001.jpg/info.json"
"smallform_0548_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0548_0002.jpg/info.json"
"smallform_0548_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0548_0003.jpg/info.json"
"smallform_0548_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0548_0004.jpg/info.json"
