mf_id = "smallform_0402.json"
mf_lang = "en"
mf_label = "Afghanistan, die Schweiz Asiens [Textzeuge a]"

[mf_data]
"smallform_0402_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0402_0001.jpg/info.json"
"smallform_0402_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0402_0002.jpg/info.json"
"smallform_0402_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0402_0003.jpg/info.json"
"smallform_0402_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0402_0004.jpg/info.json"
"smallform_0402_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0402_0005.jpg/info.json"
"smallform_0402_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0402_0006.jpg/info.json"
"smallform_0402_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0402_0007.jpg/info.json"
"smallform_0402_0008.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0402_0008.jpg/info.json"
"smallform_0402_0009.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0402_0009.jpg/info.json"
"smallform_0402_0010.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0402_0010.jpg/info.json"
