mf_id = "smallform_0667.json"
mf_lang = "en"
mf_label = "Besinnung auf Thomas Jefferson [Textzeuge b = Durchschlag]"

[mf_data]
smallform_0667_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0667_0001.jpg/info.json"
smallform_0667_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0667_0002.jpg/info.json"
smallform_0667_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0667_0003.jpg/info.json"
smallform_0667_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0667_0004.jpg/info.json"
smallform_0667_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0667_0005.jpg/info.json"
smallform_0667_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0667_0006.jpg/info.json"
