mf_id = "smallform_0159.json"
mf_lang = "en"
mf_label = "Im Elbursgebirge (oder: Im persischen Hochgebirge)"

[mf_data]
smallform_0159_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0159_0001.jpg/info.json"
smallform_0159_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0159_0002.jpg/info.json"
smallform_0159_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0159_0003.jpg/info.json"
smallform_0159_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0159_0004.jpg/info.json"
smallform_0159_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0159_0005.jpg/info.json"
smallform_0159_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0159_0006.jpg/info.json"
smallform_0159_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0159_0007.jpg/info.json"
smallform_0159_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0159_0008.jpg/info.json"
smallform_0159_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0159_0009.jpg/info.json"
