mf_id = "smallform_0008.json"
mf_lang = "en"
mf_label = "[Ena Bernstein = eine Frau zu sehen]"

[mf_data]
"smallform_0008_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0001.jpg/info.json"
"smallform_0008_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0002.jpg/info.json"
"smallform_0008_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0003.jpg/info.json"
"smallform_0008_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0004.jpg/info.json"
"smallform_0008_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0005.jpg/info.json"
"smallform_0008_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0006.jpg/info.json"
"smallform_0008_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0007.jpg/info.json"
"smallform_0008_0008.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0008.jpg/info.json"
"smallform_0008_0009.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0009.jpg/info.json"
"smallform_0008_0010.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0010.jpg/info.json"
"smallform_0008_0011.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0011.jpg/info.json"
"smallform_0008_0012.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0012.jpg/info.json"
"smallform_0008_0013.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0013.jpg/info.json"
"smallform_0008_0014.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0014.jpg/info.json"
"smallform_0008_0015.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0015.jpg/info.json"
"smallform_0008_0016.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0016.jpg/info.json"
"smallform_0008_0017.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0017.jpg/info.json"
"smallform_0008_0018.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0018.jpg/info.json"
"smallform_0008_0019.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0019.jpg/info.json"
"smallform_0008_0020.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0020.jpg/info.json"
"smallform_0008_0021.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0021.jpg/info.json"
"smallform_0008_0022.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0022.jpg/info.json"
"smallform_0008_0023.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0023.jpg/info.json"
"smallform_0008_0024.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0024.jpg/info.json"
"smallform_0008_0025.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0025.jpg/info.json"
"smallform_0008_0026.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0026.jpg/info.json"
"smallform_0008_0027.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0027.jpg/info.json"
"smallform_0008_0028.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0028.jpg/info.json"
"smallform_0008_0029.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0029.jpg/info.json"
"smallform_0008_0030.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0030.jpg/info.json"
"smallform_0008_0031.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0031.jpg/info.json"
"smallform_0008_0032.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0032.jpg/info.json"
"smallform_0008_0033.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0033.jpg/info.json"
"smallform_0008_0034.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0034.jpg/info.json"
"smallform_0008_0035.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0035.jpg/info.json"
"smallform_0008_0036.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0036.jpg/info.json"
"smallform_0008_0037.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0037.jpg/info.json"
"smallform_0008_0038.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0038.jpg/info.json"
"smallform_0008_0039.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0039.jpg/info.json"
"smallform_0008_0040.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0040.jpg/info.json"
"smallform_0008_0041.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0041.jpg/info.json"
"smallform_0008_0042.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0042.jpg/info.json"
"smallform_0008_0043.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0043.jpg/info.json"
"smallform_0008_0044.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0044.jpg/info.json"
"smallform_0008_0045.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0045.jpg/info.json"
"smallform_0008_0046.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0046.jpg/info.json"
"smallform_0008_0047.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0047.jpg/info.json"
"smallform_0008_0048.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0048.jpg/info.json"
"smallform_0008_0049.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0049.jpg/info.json"
"smallform_0008_0050.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0050.jpg/info.json"
"smallform_0008_0051.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0051.jpg/info.json"
"smallform_0008_0052.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0052.jpg/info.json"
"smallform_0008_0053.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0053.jpg/info.json"
"smallform_0008_0054.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0054.jpg/info.json"
"smallform_0008_0055.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0055.jpg/info.json"
"smallform_0008_0056.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0056.jpg/info.json"
"smallform_0008_0057.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0057.jpg/info.json"
"smallform_0008_0058.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0058.jpg/info.json"
"smallform_0008_0059.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0059.jpg/info.json"
"smallform_0008_0060.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0060.jpg/info.json"
"smallform_0008_0061.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0061.jpg/info.json"
