mf_id = "smallform_0253.json"
mf_lang = "en"
mf_label = "[Tagebuch] Thema: Lumberton. Chronologie Lumberton (20. Mai - 30. Oktober 1937)]"

[mf_data]
smallform_0253_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0001.jpg/info.json"
smallform_0253_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0002.jpg/info.json"
smallform_0253_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0003.jpg/info.json"
smallform_0253_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0004.jpg/info.json"
smallform_0253_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0005.jpg/info.json"
smallform_0253_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0006.jpg/info.json"
smallform_0253_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0007.jpg/info.json"
smallform_0253_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0008.jpg/info.json"
smallform_0253_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0009.jpg/info.json"
smallform_0253_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0010.jpg/info.json"
smallform_0253_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0011.jpg/info.json"
smallform_0253_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0012.jpg/info.json"
smallform_0253_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0013.jpg/info.json"
smallform_0253_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0014.jpg/info.json"
smallform_0253_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0015.jpg/info.json"
smallform_0253_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0016.jpg/info.json"
smallform_0253_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0017.jpg/info.json"
smallform_0253_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0018.jpg/info.json"
smallform_0253_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0019.jpg/info.json"
smallform_0253_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0020.jpg/info.json"
smallform_0253_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0021.jpg/info.json"
smallform_0253_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0022.jpg/info.json"
smallform_0253_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0253_0023.jpg/info.json"
