mf_id = "smallform_0756.json"
mf_lang = "en"
mf_label = "[Die Bucht von Bandra] [Textzeuge b - Abschrift]"

[mf_data]
"smallform_0756_0021.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0756_0021.jpg/info.json"
"smallform_0756_0022.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0756_0022.jpg/info.json"
