mf_id = "smallform_0343.json"
mf_lang = "en"
mf_label = "1. Cihil Sutun [Textzeuge a]"

[mf_data]
smallform_0343_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0343_0002.jpg/info.json"
smallform_0343_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0343_0003.jpg/info.json"
smallform_0343_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0343_0004.jpg/info.json"
