mf_id = "smallform_0074.json"
mf_lang = "en"
mf_label = "Cedern und Schneefelder des Libanon"

[mf_data]
"smallform_0074_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0074_0001.jpg/info.json"
