mf_id = "smallform_0162.json"
mf_lang = "en"
mf_label = "Besuch bei einem Perser auf dem Land"

[mf_data]
smallform_0162_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0001.jpg/info.json"
smallform_0162_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0002.jpg/info.json"
smallform_0162_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0003.jpg/info.json"
smallform_0162_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0004.jpg/info.json"
smallform_0162_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0005.jpg/info.json"
smallform_0162_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0006.jpg/info.json"
smallform_0162_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0007.jpg/info.json"
smallform_0162_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0008.jpg/info.json"
smallform_0162_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0009.jpg/info.json"
smallform_0162_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0010.jpg/info.json"
smallform_0162_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0011.jpg/info.json"
smallform_0162_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0012.jpg/info.json"
