mf_id = "smallform_0138.json"
mf_lang = "en"
mf_label = "Beni Zainab "

[mf_data]
smallform_0138_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0001.jpg/info.json"
smallform_0138_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0002.jpg/info.json"
smallform_0138_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0003.jpg/info.json"
smallform_0138_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0004.jpg/info.json"
smallform_0138_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0005.jpg/info.json"
smallform_0138_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0006.jpg/info.json"
smallform_0138_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0007.jpg/info.json"
smallform_0138_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0008.jpg/info.json"
smallform_0138_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0009.jpg/info.json"
smallform_0138_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0010.jpg/info.json"
smallform_0138_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0011.jpg/info.json"
smallform_0138_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0012.jpg/info.json"
smallform_0138_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0013.jpg/info.json"
smallform_0138_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0014.jpg/info.json"
smallform_0138_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0015.jpg/info.json"
smallform_0138_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0016.jpg/info.json"
smallform_0138_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0017.jpg/info.json"
smallform_0138_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0018.jpg/info.json"
smallform_0138_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0019.jpg/info.json"
smallform_0138_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0020.jpg/info.json"
smallform_0138_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0021.jpg/info.json"
smallform_0138_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0022.jpg/info.json"
smallform_0138_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0023.jpg/info.json"
smallform_0138_024 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0024.jpg/info.json"
smallform_0138_025 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0025.jpg/info.json"
smallform_0138_026 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0026.jpg/info.json"
smallform_0138_027 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0138_0027.jpg/info.json"
