mf_id = "smallform_0145.json"
mf_lang = "en"
mf_label = "Ein Auswanderer "

[mf_data]
smallform_0145_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0145_0001.jpg/info.json"
smallform_0145_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0145_0002.jpg/info.json"
smallform_0145_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0145_0003.jpg/info.json"
smallform_0145_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0145_0004.jpg/info.json"
smallform_0145_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0145_0005.jpg/info.json"
smallform_0145_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0145_0006.jpg/info.json"
