mf_id = "smallform_0776.json"
mf_lang = "en"
mf_label = "Über das Heroische bei Stefan George"

[mf_data]
smallform_0776_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_001.tif/info.json"
smallform_0776_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_002.tif/info.json"
smallform_0776_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_003.tif/info.json"
smallform_0776_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_004.tif/info.json"
smallform_0776_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_005.tif/info.json"
smallform_0776_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_006.tif/info.json"
smallform_0776_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_007.tif/info.json"
smallform_0776_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_008.tif/info.json"
smallform_0776_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_009.tif/info.json"
smallform_0776_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_010.tif/info.json"
smallform_0776_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_011.tif/info.json"
smallform_0776_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_012.tif/info.json"
smallform_0776_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_013.tif/info.json"
smallform_0776_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_014.tif/info.json"
smallform_0776_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_015.tif/info.json"
smallform_0776_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_016.tif/info.json"
smallform_0776_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_017.tif/info.json"
smallform_0776_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_018.tif/info.json"
smallform_0776_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_019.tif/info.json"
smallform_0776_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_020.tif/info.json"
smallform_0776_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_021.tif/info.json"
smallform_0776_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_022.tif/info.json"
smallform_0776_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_023.tif/info.json"
smallform_0776_024 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_024.tif/info.json"
smallform_0776_025 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_025.tif/info.json"
smallform_0776_026 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_026.tif/info.json"
smallform_0776_027 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_027.tif/info.json"
smallform_0776_028 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_028.tif/info.json"
smallform_0776_029 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_029.tif/info.json"
smallform_0776_030 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_030.tif/info.json"
smallform_0776_031 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_031.tif/info.json"
smallform_0776_032 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_032.tif/info.json"
smallform_0776_033 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_033.tif/info.json"
smallform_0776_034 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_034.tif/info.json"
smallform_0776_035 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_035.tif/info.json"
smallform_0776_036 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_036.tif/info.json"
smallform_0776_037 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_037.tif/info.json"
smallform_0776_038 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_038.tif/info.json"
smallform_0776_039 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_039.tif/info.json"
smallform_0776_040 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_040.tif/info.json"
smallform_0776_041 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0776_041.tif/info.json"
