mf_id = "smallform_0153.json"
mf_lang = "en"
mf_label = "Ein Flussübergang in Irak"

[mf_data]
"smallform_0153_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0153_0001.jpg/info.json"
