mf_id = "smallform_0089.json"
mf_lang = "en"
mf_label = "Ukheidir"

[mf_data]
smallform_0089_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0089_0001.jpg/info.json"
smallform_0089_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0089_0002.jpg/info.json"
smallform_0089_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0089_0003.jpg/info.json"
smallform_0089_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0089_0004.jpg/info.json"
smallform_0089_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0089_0005.jpg/info.json"
smallform_0089_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0089_0006.jpg/info.json"
smallform_0089_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0089_0007.jpg/info.json"
smallform_0089_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0089_0008.jpg/info.json"
smallform_0089_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0089_0009.jpg/info.json"
smallform_0089_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0089_0010.jpg/info.json"
smallform_0089_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0089_0011.jpg/info.json"
