mf_id = "smallform_0163.json"
mf_lang = "en"
mf_label = "Die Mission"

[mf_data]
"smallform_0163_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0163_0001.jpg/info.json"
"smallform_0163_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0163_0002.jpg/info.json"
"smallform_0163_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0163_0003.jpg/info.json"
"smallform_0163_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0163_0004.jpg/info.json"
"smallform_0163_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0163_0005.jpg/info.json"
"smallform_0163_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0163_0006.jpg/info.json"
"smallform_0163_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0163_0007.jpg/info.json"
