mf_id = "smallform_0593.json"
mf_lang = "en"
mf_label = "Aus Tetuan I-IV (1942) [Textzeuge a]"

[mf_data]
smallform_0593_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0593_0001.jpg/info.json"
smallform_0593_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0593_0002.jpg/info.json"
smallform_0593_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0593_0003.jpg/info.json"
smallform_0593_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0593_0004.jpg/info.json"
smallform_0593_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0593_0005.jpg/info.json"
smallform_0593_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0593_0006.jpg/info.json"
smallform_0593_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0593_0007.jpg/info.json"
smallform_0593_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0593_0008.jpg/info.json"
smallform_0593_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0593_0009.jpg/info.json"
