mf_id = "smallform_0557.json"
mf_lang = "en"
mf_label = "La Jeunesse française au Maroc"

[mf_data]
smallform_0557_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0557_0001.jpg/info.json"
smallform_0557_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0557_0002.jpg/info.json"
smallform_0557_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0557_0003.jpg/info.json"
smallform_0557_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0557_0004.jpg/info.json"
smallform_0557_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0557_0005.jpg/info.json"
smallform_0557_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0557_0006.jpg/info.json"
