mf_id = "smallform_0680.json"
mf_lang = "en"
mf_label = "[Inhaltsverzeichnis: Die vierzig Säulen der Erinnerung]"

[mf_data]
"smallform_0680_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0680_0001.jpg/info.json"
