mf_id = "smallform_0020.json"
mf_lang = "en"
mf_label = "Stellung der Jugend"

[mf_data]
smallform_0020_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0001.jpg/info.json"
smallform_0020_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0002.jpg/info.json"
smallform_0020_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0003.jpg/info.json"
smallform_0020_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0004.jpg/info.json"
smallform_0020_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0005.jpg/info.json"
smallform_0020_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0006.jpg/info.json"
smallform_0020_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0007.jpg/info.json"
smallform_0020_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0008.jpg/info.json"
smallform_0020_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0009.jpg/info.json"
smallform_0020_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0010.jpg/info.json"
smallform_0020_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0011.jpg/info.json"
smallform_0020_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0012.jpg/info.json"
smallform_0020_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0013.jpg/info.json"
smallform_0020_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0020_0014.jpg/info.json"
