mf_id = "smallform_0081.json"
mf_lang = "en"
mf_label = "Eine Fahrt nach Damaskus"

[mf_data]
smallform_0081_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0081_0001.jpg/info.json"
smallform_0081_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0081_0002.jpg/info.json"
smallform_0081_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0081_0003.jpg/info.json"
smallform_0081_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0081_0004.jpg/info.json"
smallform_0081_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0081_0005.jpg/info.json"
