mf_id = "smallform_0677.json"
mf_lang = "en"
mf_label = "Die persischen Gärten [Textzeuge b]"

[mf_data]
smallform_0677_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0677_0001.jpg/info.json"
