mf_id = "smallform_0213.json"
mf_lang = "en"
mf_label = "Die \"Drakooni\" kommen nach Petschur!"

[mf_data]
"smallform_0213_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0213_0001.jpg/info.json"
"smallform_0213_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0213_0002.jpg/info.json"
"smallform_0213_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0213_0003.jpg/info.json"
