mf_id = "smallform_0492.json"
mf_lang = "en"
mf_label = "Junge portugiesische Malerei"

[mf_data]
smallform_0492_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0001.jpg/info.json"
smallform_0492_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0002.jpg/info.json"
smallform_0492_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0003.jpg/info.json"
smallform_0492_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0004.jpg/info.json"
smallform_0492_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0005.jpg/info.json"
smallform_0492_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0006.jpg/info.json"
smallform_0492_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0007.jpg/info.json"
smallform_0492_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0008.jpg/info.json"
smallform_0492_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0009.jpg/info.json"
smallform_0492_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0010.jpg/info.json"
smallform_0492_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0011.jpg/info.json"
smallform_0492_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0012.jpg/info.json"
smallform_0492_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0013.jpg/info.json"
smallform_0492_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0014.jpg/info.json"
smallform_0492_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0015.jpg/info.json"
smallform_0492_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0016.jpg/info.json"
smallform_0492_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0017.jpg/info.json"
smallform_0492_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0018.jpg/info.json"
smallform_0492_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0019.jpg/info.json"
smallform_0492_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0020.jpg/info.json"
smallform_0492_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0021.jpg/info.json"
smallform_0492_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0492_0022.jpg/info.json"
