mf_id = "smallform_0575.json"
mf_lang = "en"
mf_label = "Der Blick auf die Berge"

[mf_data]
smallform_0575_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0575_0001.jpg/info.json"
smallform_0575_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0575_0002.jpg/info.json"
smallform_0575_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0575_0003.jpg/info.json"
smallform_0575_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0575_0004.jpg/info.json"
smallform_0575_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0575_0005.jpg/info.json"
