mf_id = "smallform_0353.json"
mf_lang = "en"
mf_label = "10. Die Bucht von Bandra [Textzeuge a]"

[mf_data]
smallform_0353_052 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0353_0052.jpg/info.json"
smallform_0353_053 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0353_0053.jpg/info.json"
smallform_0353_054 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0353_0054.jpg/info.json"
