mf_id = "smallform_0196.json"
mf_lang = "en"
mf_label = "Aus der Arbeiterbewegung Amerikas: John L. Lewis, Präsident der C.J.O. kämpft um das Recht, Industrielle Gewerkschaften zu organisieren und kollektiv zu verhandeln"

[mf_data]
smallform_0196_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0196_0001.jpg/info.json"
smallform_0196_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0196_0002.jpg/info.json"
smallform_0196_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0196_0003.jpg/info.json"
smallform_0196_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0196_0004.jpg/info.json"
smallform_0196_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0196_0005.jpg/info.json"
smallform_0196_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0196_0006.jpg/info.json"
smallform_0196_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0196_0007.jpg/info.json"
smallform_0196_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0196_0008.jpg/info.json"
