mf_id = "smallform_0388.json"
mf_lang = "en"
mf_label = "Sieben russische Grenzen"

[mf_data]
smallform_0388_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0388_0001.jpg/info.json"
smallform_0388_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0388_0002.jpg/info.json"
smallform_0388_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0388_0003.jpg/info.json"
smallform_0388_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0388_0004.jpg/info.json"
smallform_0388_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0388_0005.jpg/info.json"
