mf_id = "smallform_0068.json"
mf_lang = "en"
mf_label = "Vom Mittelmeer zum Atlantischen Ozean: Andorraner, Basken und Zigeuner"

[mf_data]
smallform_0068_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0068_0001.jpg/info.json"
smallform_0068_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0068_0002.jpg/info.json"
smallform_0068_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0068_0003.jpg/info.json"
smallform_0068_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0068_0004.jpg/info.json"
smallform_0068_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0068_0005.jpg/info.json"
smallform_0068_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0068_0006.jpg/info.json"
