mf_id = "smallform_0642.json"
mf_lang = "en"
mf_label = "Das Märchen von der gefangenen Prinzessin [Textzeuge b]"

[mf_data]
smallform_0642_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0001.jpg/info.json"
smallform_0642_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0002.jpg/info.json"
smallform_0642_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0003.jpg/info.json"
smallform_0642_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0004.jpg/info.json"
smallform_0642_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0005.jpg/info.json"
smallform_0642_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0006.jpg/info.json"
smallform_0642_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0007.jpg/info.json"
smallform_0642_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0008.jpg/info.json"
smallform_0642_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0009.jpg/info.json"
smallform_0642_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0010.jpg/info.json"
smallform_0642_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0011.jpg/info.json"
smallform_0642_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0012.jpg/info.json"
smallform_0642_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0013.jpg/info.json"
smallform_0642_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0014.jpg/info.json"
smallform_0642_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0015.jpg/info.json"
smallform_0642_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0016.jpg/info.json"
smallform_0642_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0642_0017.jpg/info.json"
