mf_id = "smallform_0636.json"
mf_lang = "en"
mf_label = "Römische Skizze [Textzeuge a]"

[mf_data]
smallform_0636_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0001.jpg/info.json"
smallform_0636_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0002.jpg/info.json"
smallform_0636_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0003.jpg/info.json"
smallform_0636_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0004.jpg/info.json"
smallform_0636_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0005.jpg/info.json"
smallform_0636_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0006.jpg/info.json"
smallform_0636_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0007.jpg/info.json"
smallform_0636_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0008.jpg/info.json"
smallform_0636_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0009.jpg/info.json"
smallform_0636_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0010.jpg/info.json"
smallform_0636_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0011.jpg/info.json"
smallform_0636_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0012.jpg/info.json"
smallform_0636_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0013.jpg/info.json"
smallform_0636_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0014.jpg/info.json"
smallform_0636_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0015.jpg/info.json"
smallform_0636_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0636_0016.jpg/info.json"
