mf_id = "smallform_0763.json"
mf_lang = "en"
mf_label = "Trabzon, der Abschied vom Meer  [Textzeuge c - Fotokopie]"

[mf_data]
smallform_0763_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0763_0005.jpg/info.json"
smallform_0763_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0763_0006.jpg/info.json"
smallform_0763_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0763_0007.jpg/info.json"
smallform_0763_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0763_0008.jpg/info.json"
