mf_id = "smallform_0324.json"
mf_lang = "en"
mf_label = "Dreimal der Hindukusch"

[mf_data]
"smallform_0324_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0324_0001.jpg/info.json"
"smallform_0324_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0324_0002.jpg/info.json"
"smallform_0324_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0324_0003.jpg/info.json"
"smallform_0324_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0324_0004.jpg/info.json"
"smallform_0324_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0324_0005.jpg/info.json"
