mf_id = "smallform_0650.json"
mf_lang = "en"
mf_label = "Der Fluss [Textzeuge b]"

[mf_data]
smallform_0650_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0650_0001.jpg/info.json"
smallform_0650_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0650_0002.jpg/info.json"
smallform_0650_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0650_0003.jpg/info.json"
smallform_0650_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0650_0004.jpg/info.json"
smallform_0650_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0650_0005.jpg/info.json"
smallform_0650_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0650_0006.jpg/info.json"
smallform_0650_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0650_0007.jpg/info.json"
smallform_0650_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0650_0008.jpg/info.json"
smallform_0650_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0650_0009.jpg/info.json"
smallform_0650_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0650_0010.jpg/info.json"
