mf_id = "smallform_0570.json"
mf_lang = "en"
mf_label = "Marokkanische Erntezeit"

[mf_data]
"smallform_0570_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0570_0001.jpg/info.json"
"smallform_0570_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0570_0002.jpg/info.json"
"smallform_0570_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0570_0003.jpg/info.json"
"smallform_0570_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0570_0004.jpg/info.json"
"smallform_0570_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0570_0005.jpg/info.json"
smallform_0570_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0570_001.tif/info.json"
