mf_id = "letter_0878.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Storrer-Madelung, Florianna; Korrespondenz"

[mf_data]
letter_0878_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0878_001.jpg/info.json"
letter_0878_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0878_002.jpg/info.json"
letter_0878_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0878_003.jpg/info.json"
letter_0878_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0878_004.jpg/info.json"
