mf_id = "letter_0830.json"
mf_lang = "en"
mf_label = "Kopie: Schwarzenbach, Annemarie an Schlumberger, Dominique; Korrespondenz"

[mf_data]
letter_0830_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0830_001.jpg/info.json"
letter_0830_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0830_002.jpg/info.json"
letter_0830_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0830_003.jpg/info.json"
letter_0830_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0830_004.jpg/info.json"
