mf_id = "letter_0621.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0621_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0621_001.jpg/info.json"
letter_0621_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0621_002.jpg/info.json"
letter_0621_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0621_003.jpg/info.json"
letter_0621_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0621_004.jpg/info.json"
