mf_id = "letter_0763.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Merz, Ernst; Korrespondenz"

[mf_data]
letter_0763_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0763_001.jpg/info.json"
letter_0763_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0763_002.jpg/info.json"
letter_0763_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0763_003.jpg/info.json"
letter_0763_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0763_004.jpg/info.json"
