mf_id = "letter_0794.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Wolkenberg, Alfred; Korrespondenz"

[mf_data]
letter_0794_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0794_001.jpg/info.json"
letter_0794_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0794_002.jpg/info.json"
