mf_id = "letter_0641.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0641_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0641_001.jpg/info.json"
letter_0641_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0641_002.jpg/info.json"
letter_0641_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0641_003.jpg/info.json"
