mf_id = "letter_0889.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Nougarède, Jaqueline"

[mf_data]
letter_0889_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0889_001.jpg/info.json"
letter_0889_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0889_002.jpg/info.json"
letter_0889_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0889_003.jpg/info.json"
letter_0889_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0889_004.jpg/info.json"
letter_0889_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0889_005.jpg/info.json"
