mf_id = "letter_0757.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Merz, Ernst; Korrespondenz"

[mf_data]
letter_0757_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0757_001.jpg/info.json"
letter_0757_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0757_002.jpg/info.json"
letter_0757_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0757_003.jpg/info.json"
letter_0757_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0757_004.jpg/info.json"
