mf_id = "letter_0774.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Merz, Ernst; Korrespondenz"

[mf_data]
letter_0774_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0774_001.jpg/info.json"
letter_0774_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0774_002.jpg/info.json"
letter_0774_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0774_003.jpg/info.json"
