mf_id = "letter_0868.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Storrer-Madelung, Florianna; Korrespondenz"

[mf_data]
letter_0868_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0868_001.jpg/info.json"
