mf_id = "letter_0912.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Nougarède, Jaqueline"

[mf_data]
letter_0912_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0912_001.jpg/info.json"
