mf_id = "letter_0930.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Nougarède, Jaqueline"

[mf_data]
letter_0930_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0930_001.jpg/info.json"
letter_0930_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0930_002.jpg/info.json"
letter_0930_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0930_003.jpg/info.json"
letter_0930_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0930_004.jpg/info.json"
letter_0930_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0930_005.jpg/info.json"
letter_0930_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0930_006.jpg/info.json"
