mf_id = "letter_0647.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0647_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0647_001.jpg/info.json"
letter_0647_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0647_002.jpg/info.json"
letter_0647_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0647_003.jpg/info.json"
letter_0647_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0647_004.jpg/info.json"
