mf_id = "letter_0829.json"
mf_lang = "en"
mf_label = "Kopie: Schwarzenbach, Annemarie an Schlumberger, Dominique; Korrespondenz"

[mf_data]
letter_0829_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0829_001.jpg/info.json"
