mf_id = "letter_0507.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Bodmer-Preiswerk, Marie-Louise; Korrespondenz"

[mf_data]
letter_0507_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0507_001.jpg/info.json"
letter_0507_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0507_002.jpg/info.json"
