mf_id = "letter_0807.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Wolkenberg, Alfred; Korrespondenz"

[mf_data]
letter_0807_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0807_001.jpg/info.json"
letter_0807_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0807_002.jpg/info.json"
letter_0807_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0807_003.jpg/info.json"
letter_0807_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0807_004.jpg/info.json"
