mf_id = "letter_0916.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Nougarède, Jaqueline"

[mf_data]
letter_0916_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0916_001.jpg/info.json"
letter_0916_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0916_002.jpg/info.json"
letter_0916_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0916_003.jpg/info.json"
letter_0916_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0916_004.jpg/info.json"
