mf_id = "letter_0527.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Bodmer-Preiswerk, Marie-Louise; Korrespondenz"

[mf_data]
letter_0527_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0527_001.jpg/info.json"
letter_0527_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0527_002.jpg/info.json"
letter_0527_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0527_003.jpg/info.json"
letter_0527_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0527_004.jpg/info.json"
letter_0527_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0527_005.jpg/info.json"
letter_0527_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0527_006.jpg/info.json"
