mf_id = "letter_0658.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0658_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0658_001.jpg/info.json"
letter_0658_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0658_002.jpg/info.json"
