mf_id = "letter_0653.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0653_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0653_001.jpg/info.json"
letter_0653_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0653_002.jpg/info.json"
