mf_id = "letter_0761.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Merz, Ernst; Korrespondenz"

[mf_data]
letter_0761_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0761_001.jpg/info.json"
letter_0761_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0761_002.jpg/info.json"
letter_0761_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0761_003.jpg/info.json"
letter_0761_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0761_004.jpg/info.json"
