mf_id = "letter_0512.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Bodmer-Preiswerk, Marie-Louise; Korrespondenz"

[mf_data]
letter_0512_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0512_001.jpg/info.json"
letter_0512_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0512_002.jpg/info.json"
letter_0512_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0512_003.jpg/info.json"
letter_0512_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0512_004.jpg/info.json"
letter_0512_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0512_005.jpg/info.json"
letter_0512_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0512_006.jpg/info.json"
letter_0512_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0512_007.jpg/info.json"
