mf_id = "letter_0672.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0672_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0672_001.jpg/info.json"
letter_0672_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0672_002.jpg/info.json"
