mf_id = "letter_0715.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Haushofer, Karl u. dess. Frau (Eltern von A'H'); Korrespondenz"

[mf_data]
letter_0715_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0715_001.jpg/info.json"
letter_0715_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0715_002.jpg/info.json"
