mf_id = "letter_0719.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Heer, H.; Korrespondenz"

[mf_data]
letter_0719_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0719_001.jpg/info.json"
letter_0719_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0719_002.jpg/info.json"
letter_0719_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0719_003.jpg/info.json"
letter_0719_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0719_004.jpg/info.json"
