mf_id = "letter_0766.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Merz, Ernst; Korrespondenz"

[mf_data]
letter_0766_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0766_001.jpg/info.json"
