mf_id = "letter_0836.json"
mf_lang = "en"
mf_label = "Kopie: Schwarzenbach, Annemarie an Schlumberger, Dominique; Korrespondenz"

[mf_data]
letter_0836_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0836_001.jpg/info.json"
letter_0836_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0836_002.jpg/info.json"
letter_0836_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0836_003.jpg/info.json"
