mf_id = "letter_0484.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Bodmer-Preiswerk, Marie-Louise; Korrespondenz"

[mf_data]
letter_0484_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0484_001.jpg/info.json"
letter_0484_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0484_002.jpg/info.json"
letter_0484_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0484_003.jpg/info.json"
letter_0484_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0484_004.jpg/info.json"
