mf_id = "letter_0867.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Storrer-Madelung, Florianna; Korrespondenz"

[mf_data]
letter_0867_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0867_001.jpg/info.json"
