mf_id = "letter_0533.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Bodmer-Preiswerk, Marie-Louise; Korrespondenz"

[mf_data]
letter_0533_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0533_001.jpg/info.json"
