mf_id = "letter_0495.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Bodmer-Preiswerk, Marie-Louise; Korrespondenz"

[mf_data]
letter_0495_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0495_001.jpg/info.json"
letter_0495_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0495_002.jpg/info.json"
