mf_id = "letter_0894.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Nougarède, Jaqueline"

[mf_data]
letter_0894_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0894_001.jpg/info.json"
letter_0894_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0894_002.jpg/info.json"
