mf_id = "letter_0753.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Merz, Ernst; Korrespondenz"

[mf_data]
letter_0753_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0753_001.jpg/info.json"
letter_0753_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0753_002.jpg/info.json"
letter_0753_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0753_003.jpg/info.json"
letter_0753_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0753_004.jpg/info.json"
letter_0753_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0753_005.jpg/info.json"
letter_0753_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0753_006.jpg/info.json"
