mf_id = "letter_0760.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Merz, Ernst; Korrespondenz"

[mf_data]
letter_0760_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0760_001.jpg/info.json"
letter_0760_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0760_002.jpg/info.json"
