mf_id = "letter_0622.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0622_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0622_001.jpg/info.json"
letter_0622_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0622_002.jpg/info.json"
letter_0622_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0622_003.jpg/info.json"
letter_0622_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0622_004.jpg/info.json"
letter_0622_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0622_005.jpg/info.json"
