mf_id = "letter_0852.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Storrer-Madelung, Florianna; Korrespondenz"

[mf_data]
letter_0852_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0852_001.jpg/info.json"
letter_0852_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0852_002.jpg/info.json"
