mf_id = "letter_0717.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Heer, H.; Korrespondenz"

[mf_data]
letter_0717_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0717_001.jpg/info.json"
letter_0717_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0717_002.jpg/info.json"
letter_0717_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0717_003.jpg/info.json"
