mf_id = "letter_0862.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Storrer-Madelung, Florianna; Korrespondenz"

[mf_data]
letter_0862_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0862_001.jpg/info.json"
letter_0862_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0862_002.jpg/info.json"
