mf_id = "letter_0524.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Bodmer-Preiswerk, Marie-Louise; Korrespondenz"

[mf_data]
letter_0524_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0524_001.jpg/info.json"
letter_0524_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0524_002.jpg/info.json"
