mf_id = "letter_0803.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Wolkenberg, Alfred; Korrespondenz"

[mf_data]
letter_0803_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0803_001.jpg/info.json"
letter_0803_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0803_002.jpg/info.json"
