mf_id = "letter_0899.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Nougarède, Jaqueline"

[mf_data]
letter_0899_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0899_001.jpg/info.json"
letter_0899_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0899_002.jpg/info.json"
