mf_id = "letter_0477.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Baumann, Lotti; Korrespondenz"

[mf_data]
letter_0477_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0477_001.jpg/info.json"
letter_0477_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0477_002.jpg/info.json"
letter_0477_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0477_003.jpg/info.json"
