mf_id = "letter_0781.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Merz, Ernst; Korrespondenz"

[mf_data]
letter_0781_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0781_001.jpg/info.json"
letter_0781_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0781_002.jpg/info.json"
