mf_id = "letter_0848.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Storrer-Madelung, Florianna; Korrespondenz"

[mf_data]
letter_0848_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0848_001.jpg/info.json"
letter_0848_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0848_002.jpg/info.json"
letter_0848_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0848_003.jpg/info.json"
letter_0848_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0848_004.jpg/info.json"
