mf_id = "letter_0805.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Wolkenberg, Alfred; Korrespondenz"

[mf_data]
letter_0805_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0805_001.jpg/info.json"
letter_0805_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0805_002.jpg/info.json"
