mf_id = "letter_0731.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Maillart, Ella; Korrespondenz"

[mf_data]
letter_0731_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0731_001.jpg/info.json"
letter_0731_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0731_002.jpg/info.json"
