mf_id = "letter_0665.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0665_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0665_001.jpg/info.json"
letter_0665_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0665_002.jpg/info.json"
