mf_id = "letter_0839.json"
mf_lang = "en"
mf_label = "Kopie: Schwarzenbach, Annemarie an Schlumberger, Dominique; Korrespondenz"

[mf_data]
letter_0839_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0839_001.jpg/info.json"
letter_0839_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0839_002.jpg/info.json"
letter_0839_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0839_003.jpg/info.json"
letter_0839_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0839_004.jpg/info.json"
