mf_id = "letter_0605.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Forrer, Anita; Korrespondenz"

[mf_data]
letter_0605_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0605_001.jpg/info.json"
letter_0605_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0605_002.jpg/info.json"
letter_0605_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0605_003.jpg/info.json"
