mf_id = "letter_0483.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Bodmer-Preiswerk, Marie-Louise; Korrespondenz"

[mf_data]
letter_0483_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0483_001.jpg/info.json"
letter_0483_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0483_002.jpg/info.json"
letter_0483_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0483_003.jpg/info.json"
letter_0483_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0483_004.jpg/info.json"
letter_0483_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0483_005.jpg/info.json"
