mf_id = "letter_0752.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Maillart, Dagmar; Korrespondenz"

[mf_data]
letter_0752_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0752_001.jpg/info.json"
