mf_id = "letter_0714.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Haushofer, Karl u. dess. Frau (Eltern von A'H'); Korrespondenz"

[mf_data]
letter_0714_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0714_001.jpg/info.json"
