mf_id = "longform_0023.json"
mf_lang = "en"
mf_label = "[Das Wunder des Baums] II [Textzeuge c]"

[mf_data]
"longform_0023_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0001.jpg/info.json"
"longform_0023_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0002.jpg/info.json"
"longform_0023_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0003.jpg/info.json"
"longform_0023_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0004.jpg/info.json"
"longform_0023_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0005.jpg/info.json"
"longform_0023_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0006.jpg/info.json"
"longform_0023_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0007.jpg/info.json"
"longform_0023_0008.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0008.jpg/info.json"
"longform_0023_0009.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0009.jpg/info.json"
"longform_0023_0010.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0010.jpg/info.json"
"longform_0023_0011.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0011.jpg/info.json"
"longform_0023_0012.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0012.jpg/info.json"
"longform_0023_0013.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0013.jpg/info.json"
"longform_0023_0014.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0014.jpg/info.json"
"longform_0023_0015.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0015.jpg/info.json"
"longform_0023_0016.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0016.jpg/info.json"
"longform_0023_0017.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0017.jpg/info.json"
"longform_0023_0018.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0018.jpg/info.json"
"longform_0023_0019.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0019.jpg/info.json"
"longform_0023_0020.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0020.jpg/info.json"
"longform_0023_0021.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0021.jpg/info.json"
"longform_0023_0022.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0022.jpg/info.json"
"longform_0023_0023.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0023.jpg/info.json"
"longform_0023_0024.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0024.jpg/info.json"
"longform_0023_0025.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0025.jpg/info.json"
"longform_0023_0026.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0026.jpg/info.json"
"longform_0023_0027.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0027.jpg/info.json"
"longform_0023_0028.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0028.jpg/info.json"
"longform_0023_0029.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0029.jpg/info.json"
"longform_0023_0030.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0030.jpg/info.json"
"longform_0023_0031.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0031.jpg/info.json"
"longform_0023_0032.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0032.jpg/info.json"
"longform_0023_0033.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0033.jpg/info.json"
"longform_0023_0034.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0034.jpg/info.json"
"longform_0023_0035.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0035.jpg/info.json"
"longform_0023_0036.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0036.jpg/info.json"
"longform_0023_0037.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0037.jpg/info.json"
"longform_0023_0038.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0038.jpg/info.json"
"longform_0023_0039.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0039.jpg/info.json"
"longform_0023_0040.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0040.jpg/info.json"
"longform_0023_0041.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0041.jpg/info.json"
"longform_0023_0042.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0042.jpg/info.json"
"longform_0023_0043.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0043.jpg/info.json"
"longform_0023_0044.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0044.jpg/info.json"
"longform_0023_0045.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0045.jpg/info.json"
"longform_0023_0046.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0046.jpg/info.json"
"longform_0023_0047.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0047.jpg/info.json"
"longform_0023_0048.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0048.jpg/info.json"
"longform_0023_0049.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0049.jpg/info.json"
"longform_0023_0050.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0050.jpg/info.json"
"longform_0023_0051.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0051.jpg/info.json"
"longform_0023_0052.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0052.jpg/info.json"
"longform_0023_0053.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0053.jpg/info.json"
"longform_0023_0054.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0054.jpg/info.json"
"longform_0023_0055.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0055.jpg/info.json"
"longform_0023_0056.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0056.jpg/info.json"
"longform_0023_0057.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0057.jpg/info.json"
"longform_0023_0058.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0058.jpg/info.json"
"longform_0023_0059.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0059.jpg/info.json"
"longform_0023_0060.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0060.jpg/info.json"
"longform_0023_0061.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0061.jpg/info.json"
"longform_0023_0062.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0062.jpg/info.json"
"longform_0023_0063.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0063.jpg/info.json"
"longform_0023_0064.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0064.jpg/info.json"
"longform_0023_0065.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0065.jpg/info.json"
"longform_0023_0066.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0066.jpg/info.json"
"longform_0023_0067.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0067.jpg/info.json"
"longform_0023_0068.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0068.jpg/info.json"
"longform_0023_0069.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0069.jpg/info.json"
"longform_0023_0070.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0070.jpg/info.json"
"longform_0023_0071.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0071.jpg/info.json"
"longform_0023_0072.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0072.jpg/info.json"
"longform_0023_0073.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0073.jpg/info.json"
"longform_0023_0074.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0074.jpg/info.json"
"longform_0023_0075.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0075.jpg/info.json"
"longform_0023_0076.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0076.jpg/info.json"
"longform_0023_0077.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0077.jpg/info.json"
"longform_0023_0078.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0078.jpg/info.json"
"longform_0023_0079.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0079.jpg/info.json"
"longform_0023_0080.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0080.jpg/info.json"
"longform_0023_0081.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0081.jpg/info.json"
"longform_0023_0082.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0082.jpg/info.json"
"longform_0023_0083.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0083.jpg/info.json"
"longform_0023_0084.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0084.jpg/info.json"
"longform_0023_0085.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0085.jpg/info.json"
"longform_0023_0086.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0086.jpg/info.json"
"longform_0023_0087.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0087.jpg/info.json"
"longform_0023_0088.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0088.jpg/info.json"
"longform_0023_0089.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0089.jpg/info.json"
"longform_0023_0090.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0090.jpg/info.json"
"longform_0023_0091.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0091.jpg/info.json"
"longform_0023_0092.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0092.jpg/info.json"
"longform_0023_0093.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0093.jpg/info.json"
"longform_0023_0094.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0094.jpg/info.json"
"longform_0023_0095.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0095.jpg/info.json"
"longform_0023_0096.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0096.jpg/info.json"
"longform_0023_0097.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0097.jpg/info.json"
"longform_0023_0098.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0098.jpg/info.json"
"longform_0023_0099.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0099.jpg/info.json"
"longform_0023_0100.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0100.jpg/info.json"
"longform_0023_0101.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0101.jpg/info.json"
"longform_0023_0102.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0102.jpg/info.json"
"longform_0023_0103.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0103.jpg/info.json"
"longform_0023_0104.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0104.jpg/info.json"
"longform_0023_0105.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0105.jpg/info.json"
"longform_0023_0106.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0106.jpg/info.json"
"longform_0023_0107.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0107.jpg/info.json"
"longform_0023_0108.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0108.jpg/info.json"
"longform_0023_0109.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0109.jpg/info.json"
"longform_0023_0110.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0110.jpg/info.json"
"longform_0023_0111.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0111.jpg/info.json"
"longform_0023_0112.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0112.jpg/info.json"
"longform_0023_0113.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0113.jpg/info.json"
"longform_0023_0114.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0114.jpg/info.json"
"longform_0023_0115.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0115.jpg/info.json"
"longform_0023_0116.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0116.jpg/info.json"
"longform_0023_0117.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0117.jpg/info.json"
"longform_0023_0118.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0118.jpg/info.json"
"longform_0023_0119.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0119.jpg/info.json"
"longform_0023_0120.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0120.jpg/info.json"
"longform_0023_0121.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0121.jpg/info.json"
"longform_0023_0122.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0122.jpg/info.json"
"longform_0023_0123.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0123.jpg/info.json"
"longform_0023_0124.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0124.jpg/info.json"
"longform_0023_0125.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0023_0125.jpg/info.json"
