mf_id = "longform_0007.json"
mf_lang = "en"
mf_label = "Das glückliche Tal [Tod in Persien] [Textzeuge a]"

[mf_data]
"longform_0007_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0001.jpg/info.json"
"longform_0007_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0002.jpg/info.json"
"longform_0007_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0003.jpg/info.json"
"longform_0007_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0004.jpg/info.json"
"longform_0007_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0005.jpg/info.json"
"longform_0007_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0006.jpg/info.json"
"longform_0007_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0007.jpg/info.json"
"longform_0007_0008.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0008.jpg/info.json"
"longform_0007_0009.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0009.jpg/info.json"
"longform_0007_0010.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0010.jpg/info.json"
"longform_0007_0011.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0011.jpg/info.json"
"longform_0007_0012.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0012.jpg/info.json"
"longform_0007_0013.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0013.jpg/info.json"
"longform_0007_0014.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0014.jpg/info.json"
"longform_0007_0015.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0015.jpg/info.json"
"longform_0007_0016.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0016.jpg/info.json"
"longform_0007_0017.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0017.jpg/info.json"
"longform_0007_0018.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0018.jpg/info.json"
"longform_0007_0019.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0019.jpg/info.json"
"longform_0007_0020.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0020.jpg/info.json"
"longform_0007_0021.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0021.jpg/info.json"
"longform_0007_0022.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0022.jpg/info.json"
"longform_0007_0023.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0023.jpg/info.json"
"longform_0007_0024.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0024.jpg/info.json"
"longform_0007_0025.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0025.jpg/info.json"
"longform_0007_0026.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0026.jpg/info.json"
"longform_0007_0027.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0027.jpg/info.json"
"longform_0007_0028.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0028.jpg/info.json"
"longform_0007_0029.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0029.jpg/info.json"
"longform_0007_0030.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0030.jpg/info.json"
"longform_0007_0031.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0031.jpg/info.json"
"longform_0007_0032.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0032.jpg/info.json"
"longform_0007_0033.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0033.jpg/info.json"
"longform_0007_0034.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0034.jpg/info.json"
"longform_0007_0035.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0035.jpg/info.json"
"longform_0007_0036.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0036.jpg/info.json"
"longform_0007_0037.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0037.jpg/info.json"
"longform_0007_0038.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0038.jpg/info.json"
"longform_0007_0039.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0039.jpg/info.json"
"longform_0007_0040.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0040.jpg/info.json"
"longform_0007_0041.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0041.jpg/info.json"
"longform_0007_0042.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0042.jpg/info.json"
"longform_0007_0043.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0043.jpg/info.json"
"longform_0007_0044.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0044.jpg/info.json"
"longform_0007_0045.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0045.jpg/info.json"
"longform_0007_0046.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0046.jpg/info.json"
"longform_0007_0047.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0047.jpg/info.json"
"longform_0007_0048.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0048.jpg/info.json"
"longform_0007_0049.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0049.jpg/info.json"
"longform_0007_0050.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0050.jpg/info.json"
"longform_0007_0051.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0051.jpg/info.json"
"longform_0007_0052.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0052.jpg/info.json"
"longform_0007_0053.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0053.jpg/info.json"
"longform_0007_0054.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0054.jpg/info.json"
"longform_0007_0055.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0055.jpg/info.json"
"longform_0007_0056.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0056.jpg/info.json"
"longform_0007_0057.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0057.jpg/info.json"
"longform_0007_0058.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0058.jpg/info.json"
"longform_0007_0059.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0059.jpg/info.json"
"longform_0007_0060.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0060.jpg/info.json"
"longform_0007_0061.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0061.jpg/info.json"
"longform_0007_0062.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0062.jpg/info.json"
"longform_0007_0063.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0063.jpg/info.json"
"longform_0007_0064.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0064.jpg/info.json"
"longform_0007_0065.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0065.jpg/info.json"
"longform_0007_0066.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0066.jpg/info.json"
"longform_0007_0067.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0067.jpg/info.json"
"longform_0007_0068.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0068.jpg/info.json"
"longform_0007_0069.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0069.jpg/info.json"
"longform_0007_0070.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0070.jpg/info.json"
"longform_0007_0071.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0071.jpg/info.json"
"longform_0007_0072.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0072.jpg/info.json"
"longform_0007_0073.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0073.jpg/info.json"
"longform_0007_0074.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0074.jpg/info.json"
"longform_0007_0075.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0075.jpg/info.json"
"longform_0007_0076.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0076.jpg/info.json"
"longform_0007_0077.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0077.jpg/info.json"
"longform_0007_0078.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0078.jpg/info.json"
"longform_0007_0079.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0079.jpg/info.json"
"longform_0007_0080.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0080.jpg/info.json"
"longform_0007_0081.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0081.jpg/info.json"
"longform_0007_0082.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0082.jpg/info.json"
"longform_0007_0083.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0083.jpg/info.json"
"longform_0007_0084.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0084.jpg/info.json"
"longform_0007_0085.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0085.jpg/info.json"
"longform_0007_0086.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0086.jpg/info.json"
"longform_0007_0087.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0087.jpg/info.json"
"longform_0007_0088.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0088.jpg/info.json"
"longform_0007_0089.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0089.jpg/info.json"
"longform_0007_0090.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0090.jpg/info.json"
"longform_0007_0091.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0091.jpg/info.json"
"longform_0007_0092.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0092.jpg/info.json"
"longform_0007_0093.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0093.jpg/info.json"
"longform_0007_0094.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0094.jpg/info.json"
"longform_0007_0095.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0095.jpg/info.json"
"longform_0007_0096.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0096.jpg/info.json"
"longform_0007_0097.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0097.jpg/info.json"
"longform_0007_0098.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0098.jpg/info.json"
"longform_0007_0099.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0099.jpg/info.json"
"longform_0007_0100.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0100.jpg/info.json"
"longform_0007_0101.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0101.jpg/info.json"
"longform_0007_0102.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0102.jpg/info.json"
"longform_0007_0103.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0103.jpg/info.json"
"longform_0007_0104.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0104.jpg/info.json"
"longform_0007_0105.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0105.jpg/info.json"
"longform_0007_0106.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0106.jpg/info.json"
"longform_0007_0107.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0107.jpg/info.json"
"longform_0007_0108.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0108.jpg/info.json"
"longform_0007_0109.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0109.jpg/info.json"
"longform_0007_0110.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0110.jpg/info.json"
"longform_0007_0111.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0111.jpg/info.json"
"longform_0007_0112.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0112.jpg/info.json"
"longform_0007_0113.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0113.jpg/info.json"
"longform_0007_0114.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0114.jpg/info.json"
"longform_0007_0115.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0115.jpg/info.json"
"longform_0007_0116.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0116.jpg/info.json"
"longform_0007_0117.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0117.jpg/info.json"
"longform_0007_0118.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0118.jpg/info.json"
"longform_0007_0119.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0119.jpg/info.json"
"longform_0007_0120.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0120.jpg/info.json"
"longform_0007_0121.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0121.jpg/info.json"
"longform_0007_0122.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0122.jpg/info.json"
"longform_0007_0123.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0123.jpg/info.json"
"longform_0007_0124.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0124.jpg/info.json"
"longform_0007_0125.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0125.jpg/info.json"
"longform_0007_0126.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0126.jpg/info.json"
"longform_0007_0127.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0127.jpg/info.json"
"longform_0007_0128.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0128.jpg/info.json"
