mf_id = "longform_0017.json"
mf_lang = "en"
mf_label = "[Lorenz Saladin - div. Texte]"

[mf_data]
"longform_0017_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0001.jpg/info.json"
"longform_0017_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0002.jpg/info.json"
"longform_0017_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0003.jpg/info.json"
"longform_0017_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0004.jpg/info.json"
"longform_0017_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0005.jpg/info.json"
"longform_0017_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0006.jpg/info.json"
"longform_0017_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0007.jpg/info.json"
"longform_0017_0008.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0008.jpg/info.json"
"longform_0017_0009.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0009.jpg/info.json"
"longform_0017_0010.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0010.jpg/info.json"
"longform_0017_0011.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0011.jpg/info.json"
"longform_0017_0012.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0012.jpg/info.json"
"longform_0017_0013.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0013.jpg/info.json"
"longform_0017_0014.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0014.jpg/info.json"
"longform_0017_0015.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0015.jpg/info.json"
"longform_0017_0016.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0016.jpg/info.json"
"longform_0017_0017.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0017.jpg/info.json"
"longform_0017_0018.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0018.jpg/info.json"
"longform_0017_0019.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0019.jpg/info.json"
"longform_0017_0020.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0020.jpg/info.json"
"longform_0017_0021.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0021.jpg/info.json"
"longform_0017_0022.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0022.jpg/info.json"
"longform_0017_0023.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0023.jpg/info.json"
"longform_0017_0024.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0024.jpg/info.json"
"longform_0017_0025.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0025.jpg/info.json"
"longform_0017_0026.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0026.jpg/info.json"
"longform_0017_0027.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0027.jpg/info.json"
"longform_0017_0028.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0028.jpg/info.json"
"longform_0017_0029.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0029.jpg/info.json"
"longform_0017_0030.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0030.jpg/info.json"
"longform_0017_0031.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0031.jpg/info.json"
"longform_0017_0032.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0032.jpg/info.json"
"longform_0017_0033.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0033.jpg/info.json"
"longform_0017_0034.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0034.jpg/info.json"
"longform_0017_0035.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0035.jpg/info.json"
"longform_0017_0036.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0036.jpg/info.json"
"longform_0017_0037.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0037.jpg/info.json"
"longform_0017_0038.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0038.jpg/info.json"
"longform_0017_0039.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0039.jpg/info.json"
"longform_0017_0040.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0040.jpg/info.json"
"longform_0017_0041.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0041.jpg/info.json"
"longform_0017_0042.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0042.jpg/info.json"
"longform_0017_0043.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0043.jpg/info.json"
"longform_0017_0044.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0044.jpg/info.json"
"longform_0017_0045.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0045.jpg/info.json"
"longform_0017_0046.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0046.jpg/info.json"
"longform_0017_0047.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0047.jpg/info.json"
"longform_0017_0048.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0048.jpg/info.json"
"longform_0017_0049.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0049.jpg/info.json"
"longform_0017_0050.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0050.jpg/info.json"
"longform_0017_0051.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0051.jpg/info.json"
"longform_0017_0052.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0052.jpg/info.json"
"longform_0017_0053.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0053.jpg/info.json"
"longform_0017_0054.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0054.jpg/info.json"
"longform_0017_0055.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0055.jpg/info.json"
"longform_0017_0056.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0056.jpg/info.json"
"longform_0017_0057.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0057.jpg/info.json"
"longform_0017_0058.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0058.jpg/info.json"
"longform_0017_0059.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0059.jpg/info.json"
"longform_0017_0060.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0060.jpg/info.json"
"longform_0017_0061.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0061.jpg/info.json"
"longform_0017_0062.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0062.jpg/info.json"
"longform_0017_0063.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0063.jpg/info.json"
"longform_0017_0064.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0064.jpg/info.json"
"longform_0017_0065.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0065.jpg/info.json"
"longform_0017_0066.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0017_0066.jpg/info.json"
