mf_id = "longform_0007.json"
mf_lang = "en"
mf_label = "Das glückliche Tal [Tod in Persien] [Textzeuge a]"

[mf_data]
longform_0007_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0001.jpg/info.json"
longform_0007_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0002.jpg/info.json"
longform_0007_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0003.jpg/info.json"
longform_0007_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0004.jpg/info.json"
longform_0007_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0005.jpg/info.json"
longform_0007_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0006.jpg/info.json"
longform_0007_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0007.jpg/info.json"
longform_0007_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0008.jpg/info.json"
longform_0007_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0009.jpg/info.json"
longform_0007_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0010.jpg/info.json"
longform_0007_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0011.jpg/info.json"
longform_0007_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0012.jpg/info.json"
longform_0007_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0013.jpg/info.json"
longform_0007_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0014.jpg/info.json"
longform_0007_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0015.jpg/info.json"
longform_0007_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0016.jpg/info.json"
longform_0007_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0017.jpg/info.json"
longform_0007_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0018.jpg/info.json"
longform_0007_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0019.jpg/info.json"
longform_0007_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0020.jpg/info.json"
longform_0007_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0021.jpg/info.json"
longform_0007_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0022.jpg/info.json"
longform_0007_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0023.jpg/info.json"
longform_0007_024 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0024.jpg/info.json"
longform_0007_025 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0025.jpg/info.json"
longform_0007_026 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0026.jpg/info.json"
longform_0007_027 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0027.jpg/info.json"
longform_0007_028 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0028.jpg/info.json"
longform_0007_029 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0029.jpg/info.json"
longform_0007_030 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0030.jpg/info.json"
longform_0007_031 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0031.jpg/info.json"
longform_0007_032 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0032.jpg/info.json"
longform_0007_033 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0033.jpg/info.json"
longform_0007_034 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0034.jpg/info.json"
longform_0007_035 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0035.jpg/info.json"
longform_0007_036 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0036.jpg/info.json"
longform_0007_037 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0037.jpg/info.json"
longform_0007_038 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0038.jpg/info.json"
longform_0007_039 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0039.jpg/info.json"
longform_0007_040 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0040.jpg/info.json"
longform_0007_041 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0041.jpg/info.json"
longform_0007_042 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0042.jpg/info.json"
longform_0007_043 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0043.jpg/info.json"
longform_0007_044 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0044.jpg/info.json"
longform_0007_045 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0045.jpg/info.json"
longform_0007_046 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0046.jpg/info.json"
longform_0007_047 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0047.jpg/info.json"
longform_0007_048 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0048.jpg/info.json"
longform_0007_049 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0049.jpg/info.json"
longform_0007_050 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0050.jpg/info.json"
longform_0007_051 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0051.jpg/info.json"
longform_0007_052 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0052.jpg/info.json"
longform_0007_053 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0053.jpg/info.json"
longform_0007_054 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0054.jpg/info.json"
longform_0007_055 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0055.jpg/info.json"
longform_0007_056 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0056.jpg/info.json"
longform_0007_057 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0057.jpg/info.json"
longform_0007_058 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0058.jpg/info.json"
longform_0007_059 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0059.jpg/info.json"
longform_0007_060 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0060.jpg/info.json"
longform_0007_061 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0061.jpg/info.json"
longform_0007_062 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0062.jpg/info.json"
longform_0007_063 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0063.jpg/info.json"
longform_0007_064 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0064.jpg/info.json"
longform_0007_065 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0065.jpg/info.json"
longform_0007_066 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0066.jpg/info.json"
longform_0007_067 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0067.jpg/info.json"
longform_0007_068 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0068.jpg/info.json"
longform_0007_069 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0069.jpg/info.json"
longform_0007_070 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0070.jpg/info.json"
longform_0007_071 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0071.jpg/info.json"
longform_0007_072 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0072.jpg/info.json"
longform_0007_073 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0073.jpg/info.json"
longform_0007_074 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0074.jpg/info.json"
longform_0007_075 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0075.jpg/info.json"
longform_0007_076 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0076.jpg/info.json"
longform_0007_077 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0077.jpg/info.json"
longform_0007_078 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0078.jpg/info.json"
longform_0007_079 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0079.jpg/info.json"
longform_0007_080 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0080.jpg/info.json"
longform_0007_081 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0081.jpg/info.json"
longform_0007_082 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0082.jpg/info.json"
longform_0007_083 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0083.jpg/info.json"
longform_0007_084 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0084.jpg/info.json"
longform_0007_085 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0085.jpg/info.json"
longform_0007_086 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0086.jpg/info.json"
longform_0007_087 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0087.jpg/info.json"
longform_0007_088 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0088.jpg/info.json"
longform_0007_089 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0089.jpg/info.json"
longform_0007_090 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0090.jpg/info.json"
longform_0007_091 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0091.jpg/info.json"
longform_0007_092 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0092.jpg/info.json"
longform_0007_093 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0093.jpg/info.json"
longform_0007_094 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0094.jpg/info.json"
longform_0007_095 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0095.jpg/info.json"
longform_0007_096 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0096.jpg/info.json"
longform_0007_097 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0097.jpg/info.json"
longform_0007_098 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0098.jpg/info.json"
longform_0007_099 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0099.jpg/info.json"
longform_0007_100 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0100.jpg/info.json"
longform_0007_101 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0101.jpg/info.json"
longform_0007_102 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0102.jpg/info.json"
longform_0007_103 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0103.jpg/info.json"
longform_0007_104 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0104.jpg/info.json"
longform_0007_105 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0105.jpg/info.json"
longform_0007_106 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0106.jpg/info.json"
longform_0007_107 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0107.jpg/info.json"
longform_0007_108 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0108.jpg/info.json"
longform_0007_109 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0109.jpg/info.json"
longform_0007_110 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0110.jpg/info.json"
longform_0007_111 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0111.jpg/info.json"
longform_0007_112 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0112.jpg/info.json"
longform_0007_113 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0113.jpg/info.json"
longform_0007_114 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0114.jpg/info.json"
longform_0007_115 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0115.jpg/info.json"
longform_0007_116 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0116.jpg/info.json"
longform_0007_117 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0117.jpg/info.json"
longform_0007_118 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0118.jpg/info.json"
longform_0007_119 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0119.jpg/info.json"
longform_0007_120 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0120.jpg/info.json"
longform_0007_121 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0121.jpg/info.json"
longform_0007_122 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0122.jpg/info.json"
longform_0007_123 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0123.jpg/info.json"
longform_0007_124 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0124.jpg/info.json"
longform_0007_125 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0125.jpg/info.json"
longform_0007_126 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0126.jpg/info.json"
longform_0007_127 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0127.jpg/info.json"
longform_0007_128 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0007_0128.jpg/info.json"
