mf_id = "longform_0009.json"
mf_lang = "en"
mf_label = "Lorenz Saladin. Sein Weg zum Himmelsgebirge. Ein Leben für die Berge"

[mf_data]
longform_0009_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0001.jpg/info.json"
longform_0009_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0002.jpg/info.json"
longform_0009_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0003.jpg/info.json"
longform_0009_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0004.jpg/info.json"
longform_0009_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0005.jpg/info.json"
longform_0009_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0006.jpg/info.json"
longform_0009_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0007.jpg/info.json"
longform_0009_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0008.jpg/info.json"
longform_0009_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0009.jpg/info.json"
longform_0009_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0010.jpg/info.json"
longform_0009_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0011.jpg/info.json"
longform_0009_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0012.jpg/info.json"
longform_0009_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0013.jpg/info.json"
longform_0009_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0014.jpg/info.json"
longform_0009_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0015.jpg/info.json"
longform_0009_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0016.jpg/info.json"
longform_0009_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0017.jpg/info.json"
longform_0009_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0018.jpg/info.json"
longform_0009_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0019.jpg/info.json"
longform_0009_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0020.jpg/info.json"
longform_0009_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0021.jpg/info.json"
longform_0009_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0022.jpg/info.json"
longform_0009_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0023.jpg/info.json"
longform_0009_024 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0024.jpg/info.json"
longform_0009_025 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0025.jpg/info.json"
longform_0009_026 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0026.jpg/info.json"
longform_0009_027 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0027.jpg/info.json"
longform_0009_028 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0028.jpg/info.json"
longform_0009_029 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0029.jpg/info.json"
longform_0009_030 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0030.jpg/info.json"
longform_0009_031 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0031.jpg/info.json"
longform_0009_032 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0032.jpg/info.json"
longform_0009_033 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0033.jpg/info.json"
longform_0009_034 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0034.jpg/info.json"
longform_0009_035 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0035.jpg/info.json"
longform_0009_036 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0036.jpg/info.json"
longform_0009_037 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0037.jpg/info.json"
longform_0009_038 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0038.jpg/info.json"
longform_0009_039 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0039.jpg/info.json"
longform_0009_040 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0040.jpg/info.json"
longform_0009_041 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0041.jpg/info.json"
longform_0009_042 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0042.jpg/info.json"
longform_0009_043 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0043.jpg/info.json"
longform_0009_044 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0044.jpg/info.json"
longform_0009_045 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0045.jpg/info.json"
longform_0009_046 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0046.jpg/info.json"
longform_0009_047 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0047.jpg/info.json"
longform_0009_048 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0048.jpg/info.json"
longform_0009_049 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0049.jpg/info.json"
longform_0009_050 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0050.jpg/info.json"
longform_0009_051 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0051.jpg/info.json"
longform_0009_052 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0052.jpg/info.json"
longform_0009_053 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0053.jpg/info.json"
longform_0009_054 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0054.jpg/info.json"
longform_0009_055 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0055.jpg/info.json"
longform_0009_056 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0056.jpg/info.json"
longform_0009_057 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0057.jpg/info.json"
longform_0009_058 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0058.jpg/info.json"
longform_0009_059 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0059.jpg/info.json"
longform_0009_060 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0060.jpg/info.json"
longform_0009_061 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0061.jpg/info.json"
longform_0009_062 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0062.jpg/info.json"
longform_0009_063 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0063.jpg/info.json"
longform_0009_064 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0064.jpg/info.json"
longform_0009_065 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0065.jpg/info.json"
longform_0009_066 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0066.jpg/info.json"
longform_0009_067 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0067.jpg/info.json"
longform_0009_068 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0068.jpg/info.json"
longform_0009_069 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0069.jpg/info.json"
longform_0009_070 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0070.jpg/info.json"
longform_0009_071 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0071.jpg/info.json"
longform_0009_072 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0072.jpg/info.json"
longform_0009_073 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0073.jpg/info.json"
longform_0009_074 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0074.jpg/info.json"
longform_0009_075 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0075.jpg/info.json"
longform_0009_076 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0076.jpg/info.json"
longform_0009_077 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0077.jpg/info.json"
longform_0009_078 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0078.jpg/info.json"
longform_0009_079 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0079.jpg/info.json"
longform_0009_080 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0080.jpg/info.json"
longform_0009_081 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0081.jpg/info.json"
longform_0009_082 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0082.jpg/info.json"
longform_0009_083 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0083.jpg/info.json"
longform_0009_084 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0084.jpg/info.json"
longform_0009_085 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0085.jpg/info.json"
longform_0009_086 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0086.jpg/info.json"
longform_0009_087 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0087.jpg/info.json"
longform_0009_088 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0088.jpg/info.json"
longform_0009_089 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0089.jpg/info.json"
longform_0009_090 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0090.jpg/info.json"
longform_0009_091 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0091.jpg/info.json"
longform_0009_092 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0092.jpg/info.json"
longform_0009_093 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0093.jpg/info.json"
longform_0009_094 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0094.jpg/info.json"
longform_0009_095 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0095.jpg/info.json"
longform_0009_096 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0096.jpg/info.json"
longform_0009_097 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0097.jpg/info.json"
longform_0009_098 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0098.jpg/info.json"
longform_0009_099 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0099.jpg/info.json"
longform_0009_100 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0100.jpg/info.json"
longform_0009_101 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0101.jpg/info.json"
longform_0009_102 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0102.jpg/info.json"
longform_0009_103 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0103.jpg/info.json"
longform_0009_104 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0104.jpg/info.json"
longform_0009_105 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0105.jpg/info.json"
longform_0009_106 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0106.jpg/info.json"
longform_0009_107 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0107.jpg/info.json"
longform_0009_108 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0108.jpg/info.json"
longform_0009_109 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0109.jpg/info.json"
longform_0009_110 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0110.jpg/info.json"
longform_0009_111 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0111.jpg/info.json"
longform_0009_112 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0112.jpg/info.json"
longform_0009_113 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0113.jpg/info.json"
longform_0009_114 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0114.jpg/info.json"
longform_0009_115 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0115.jpg/info.json"
longform_0009_116 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0009_0116.jpg/info.json"
