mf_id = "longform_0002.json"
mf_lang = "en"
mf_label = "Cromwell. Schauspiel in acht Bildern"

[mf_data]
longform_0002_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0001.jpg/info.json"
longform_0002_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0002.jpg/info.json"
longform_0002_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0003.jpg/info.json"
longform_0002_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0004.jpg/info.json"
longform_0002_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0005.jpg/info.json"
longform_0002_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0006.jpg/info.json"
longform_0002_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0007.jpg/info.json"
longform_0002_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0008.jpg/info.json"
longform_0002_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0009.jpg/info.json"
longform_0002_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0010.jpg/info.json"
longform_0002_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0011.jpg/info.json"
longform_0002_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0012.jpg/info.json"
longform_0002_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0013.jpg/info.json"
longform_0002_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0014.jpg/info.json"
longform_0002_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0015.jpg/info.json"
longform_0002_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0016.jpg/info.json"
longform_0002_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0017.jpg/info.json"
longform_0002_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0018.jpg/info.json"
longform_0002_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0019.jpg/info.json"
longform_0002_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0020.jpg/info.json"
longform_0002_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0021.jpg/info.json"
longform_0002_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0022.jpg/info.json"
longform_0002_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0023.jpg/info.json"
longform_0002_024 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0024.jpg/info.json"
longform_0002_025 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0025.jpg/info.json"
longform_0002_026 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0026.jpg/info.json"
longform_0002_027 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0027.jpg/info.json"
longform_0002_028 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0028.jpg/info.json"
longform_0002_029 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0029.jpg/info.json"
longform_0002_030 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0030.jpg/info.json"
longform_0002_031 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0031.jpg/info.json"
longform_0002_032 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0032.jpg/info.json"
longform_0002_033 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0033.jpg/info.json"
longform_0002_034 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0034.jpg/info.json"
longform_0002_035 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0035.jpg/info.json"
longform_0002_036 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0036.jpg/info.json"
longform_0002_037 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0037.jpg/info.json"
longform_0002_038 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0038.jpg/info.json"
longform_0002_039 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0039.jpg/info.json"
longform_0002_040 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0040.jpg/info.json"
longform_0002_041 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0041.jpg/info.json"
longform_0002_042 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0042.jpg/info.json"
longform_0002_043 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0043.jpg/info.json"
longform_0002_044 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0044.jpg/info.json"
longform_0002_045 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0045.jpg/info.json"
longform_0002_046 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0046.jpg/info.json"
longform_0002_047 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0047.jpg/info.json"
longform_0002_048 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0048.jpg/info.json"
longform_0002_049 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0049.jpg/info.json"
longform_0002_050 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0050.jpg/info.json"
longform_0002_051 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0051.jpg/info.json"
longform_0002_052 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0052.jpg/info.json"
longform_0002_053 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0053.jpg/info.json"
longform_0002_054 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0054.jpg/info.json"
longform_0002_055 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0055.jpg/info.json"
longform_0002_056 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0056.jpg/info.json"
longform_0002_057 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0057.jpg/info.json"
longform_0002_058 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0058.jpg/info.json"
longform_0002_059 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0059.jpg/info.json"
longform_0002_060 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0060.jpg/info.json"
longform_0002_061 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0061.jpg/info.json"
longform_0002_062 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0062.jpg/info.json"
longform_0002_063 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0063.jpg/info.json"
longform_0002_064 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0064.jpg/info.json"
longform_0002_065 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0065.jpg/info.json"
longform_0002_066 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0066.jpg/info.json"
longform_0002_067 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0067.jpg/info.json"
longform_0002_068 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0068.jpg/info.json"
longform_0002_069 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0069.jpg/info.json"
longform_0002_070 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0070.jpg/info.json"
longform_0002_071 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0071.jpg/info.json"
longform_0002_072 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0072.jpg/info.json"
longform_0002_073 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0073.jpg/info.json"
longform_0002_074 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0074.jpg/info.json"
longform_0002_075 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0075.jpg/info.json"
longform_0002_076 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0076.jpg/info.json"
longform_0002_077 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0077.jpg/info.json"
longform_0002_078 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0078.jpg/info.json"
longform_0002_079 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0079.jpg/info.json"
longform_0002_080 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0080.jpg/info.json"
longform_0002_081 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0081.jpg/info.json"
longform_0002_082 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/longform_0002_0082.jpg/info.json"
