mf_id = "smallform_0374.json"
mf_lang = "en"
mf_label = "Die Reise nach Ghazni"

[mf_data]
smallform_0374_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0374_0001.jpg/info.json"
smallform_0374_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0374_0002.jpg/info.json"
smallform_0374_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0374_0003.jpg/info.json"
smallform_0374_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0374_0004.jpg/info.json"
smallform_0374_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0374_0005.jpg/info.json"
