mf_id = "smallform_0341.json"
mf_lang = "en"
mf_label = "Herat, Kandahar, Afghanisch Turkestan."

[mf_data]
"smallform_0341_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0341_0001.jpg/info.json"
"smallform_0341_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0341_0002.jpg/info.json"
"smallform_0341_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0341_0003.jpg/info.json"
"smallform_0341_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0341_0004.jpg/info.json"
"smallform_0341_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0341_0005.jpg/info.json"
