mf_id = "smallform_0412.json"
mf_lang = "en"
mf_label = "Nach Westen"

[mf_data]
smallform_0412_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0412_0001.jpg/info.json"
smallform_0412_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0412_0002.jpg/info.json"
smallform_0412_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0412_0003.jpg/info.json"
smallform_0412_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0412_0004.jpg/info.json"
smallform_0412_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0412_0005.jpg/info.json"
smallform_0412_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0412_0006.jpg/info.json"
