mf_id = "smallform_0673.json"
mf_lang = "en"
mf_label = ".... in einem anderen Land [Textzeuge b - Durchschlag]"

[mf_data]
"smallform_0673_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0673_0001.jpg/info.json"
"smallform_0673_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0673_0002.jpg/info.json"
"smallform_0673_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0673_0003.jpg/info.json"
"smallform_0673_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0673_0004.jpg/info.json"
