mf_id = "smallform_0724.json"
mf_lang = "en"
mf_label = "Verbotene Reise"

[mf_data]
smallform_0724_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0724_0001.jpg/info.json"
smallform_0724_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0724_0002.jpg/info.json"
smallform_0724_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0724_0003.jpg/info.json"
smallform_0724_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0724_0004.jpg/info.json"
smallform_0724_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0724_0005.jpg/info.json"
smallform_0724_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0724_0006.jpg/info.json"
