mf_id = "smallform_0366.json"
mf_lang = "en"
mf_label = "Afghanistan und der Krieg"

[mf_data]
smallform_0366_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0366_0001.jpg/info.json"
smallform_0366_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0366_0002.jpg/info.json"
smallform_0366_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0366_0003.jpg/info.json"
