mf_id = "smallform_0466.json"
mf_lang = "en"
mf_label = "Amerikanische Ereignisse: 2. Arbeiterbewegung und Landesverteidigung in den Vereinigten Staaten\n                                                                     xa0 \n                                                             \n                  "

[mf_data]
"smallform_0466_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0466_0001.jpg/info.json"
"smallform_0466_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0466_0002.jpg/info.json"
"smallform_0466_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0466_0003.jpg/info.json"
"smallform_0466_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0466_0004.jpg/info.json"
