mf_id = "smallform_0398.json"
mf_lang = "en"
mf_label = "Die Frauen Afghanistans. 1. Im Garten der schönen Mädchen von Kaisar "

[mf_data]
smallform_0398_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0398_0001.jpg/info.json"
smallform_0398_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0398_0002.jpg/info.json"
smallform_0398_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0398_0003.jpg/info.json"
