mf_id = "smallform_0696.json"
mf_lang = "en"
mf_label = "Das Tor Indiens : der Khyberpass [Textzeuge b]"

[mf_data]
smallform_0696_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0696_0001.jpg/info.json"
smallform_0696_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0696_0002.jpg/info.json"
smallform_0696_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0696_0003.jpg/info.json"
