mf_id = "smallform_0251.json"
mf_lang = "en"
mf_label = "Die Agrarreformen in den Baltischen Staaten seit dem Weltkrieg"

[mf_data]
"smallform_0251_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0251_0001.jpg/info.json"
"smallform_0251_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0251_0002.jpg/info.json"
"smallform_0251_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0251_0003.jpg/info.json"
"smallform_0251_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0251_0004.jpg/info.json"
"smallform_0251_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0251_0005.jpg/info.json"
"smallform_0251_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0251_0006.jpg/info.json"
"smallform_0251_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0251_0007.jpg/info.json"
