mf_id = "smallform_0133.json"
mf_lang = "en"
mf_label = "Fast dasselbe Leiden"

[mf_data]
"smallform_0133_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0133_0001.jpg/info.json"
"smallform_0133_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0133_0002.jpg/info.json"
"smallform_0133_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0133_0003.jpg/info.json"
"smallform_0133_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0133_0004.jpg/info.json"
"smallform_0133_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0133_0005.jpg/info.json"
"smallform_0133_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0133_0006.jpg/info.json"
