mf_id = "smallform_0693.json"
mf_lang = "en"
mf_label = "Forts. Amerikanisches Tagebuch. [III.] \"U.S.Landstrasse Nr.1\" [Textzeuge b]"

[mf_data]
"smallform_0693_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0693_0001.jpg/info.json"
"smallform_0693_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0693_0002.jpg/info.json"
