mf_id = "smallform_0025.json"
mf_lang = "en"
mf_label = "Yelinda"

[mf_data]
smallform_0025_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0001.jpg/info.json"
smallform_0025_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0002.jpg/info.json"
smallform_0025_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0003.jpg/info.json"
smallform_0025_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0004.jpg/info.json"
smallform_0025_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0005.jpg/info.json"
smallform_0025_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0006.jpg/info.json"
smallform_0025_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0007.jpg/info.json"
smallform_0025_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0008.jpg/info.json"
smallform_0025_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0009.jpg/info.json"
smallform_0025_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0010.jpg/info.json"
smallform_0025_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0011.jpg/info.json"
smallform_0025_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0012.jpg/info.json"
smallform_0025_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0013.jpg/info.json"
smallform_0025_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0014.jpg/info.json"
smallform_0025_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0015.jpg/info.json"
smallform_0025_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0016.jpg/info.json"
smallform_0025_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0017.jpg/info.json"
smallform_0025_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0018.jpg/info.json"
smallform_0025_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0019.jpg/info.json"
smallform_0025_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0020.jpg/info.json"
smallform_0025_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0021.jpg/info.json"
smallform_0025_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0022.jpg/info.json"
smallform_0025_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0023.jpg/info.json"
smallform_0025_024 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0024.jpg/info.json"
smallform_0025_025 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0025.jpg/info.json"
smallform_0025_026 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0026.jpg/info.json"
smallform_0025_027 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0027.jpg/info.json"
smallform_0025_028 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0028.jpg/info.json"
smallform_0025_029 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0029.jpg/info.json"
smallform_0025_030 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0025_0030.jpg/info.json"
