mf_id = "smallform_0660.json"
mf_lang = "en"
mf_label = "[Der Fallkenkäfig: Titelblatt und Inhaltsverzeichnis]"

[mf_data]
smallform_0660_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0660_0001.jpg/info.json"
smallform_0660_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0660_0002.jpg/info.json"
