mf_id = "smallform_0745.json"
mf_lang = "en"
mf_label = "Gespräch [Textzeuge d]"

[mf_data]
smallform_0745_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0745_0001.jpg/info.json"
smallform_0745_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0745_0002.jpg/info.json"
smallform_0745_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0745_0003.jpg/info.json"
smallform_0745_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0745_0004.jpg/info.json"
