mf_id = "smallform_0577.json"
mf_lang = "en"
mf_label = "Volubilis"

[mf_data]
"smallform_0577_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0577_0001.jpg/info.json"
"smallform_0577_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0577_0002.jpg/info.json"
"smallform_0577_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0577_0003.jpg/info.json"
"smallform_0577_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0577_0004.jpg/info.json"
"smallform_0577_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0577_0005.jpg/info.json"
