mf_id = "smallform_0727.json"
mf_lang = "en"
mf_label = "Die Reise an das Ende Amerikas"

[mf_data]
"smallform_0727_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0727_0001.jpg/info.json"
"smallform_0727_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0727_0002.jpg/info.json"
"smallform_0727_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0727_0003.jpg/info.json"
"smallform_0727_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0727_0004.jpg/info.json"
