mf_id = "smallform_0646.json"
mf_lang = "en"
mf_label = "Pariser Novelle [II]"

[mf_data]
smallform_0646_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0001.jpg/info.json"
smallform_0646_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0002.jpg/info.json"
smallform_0646_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0003.jpg/info.json"
smallform_0646_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0004.jpg/info.json"
smallform_0646_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0005.jpg/info.json"
smallform_0646_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0006.jpg/info.json"
smallform_0646_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0007.jpg/info.json"
smallform_0646_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0008.jpg/info.json"
smallform_0646_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0009.jpg/info.json"
smallform_0646_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0010.jpg/info.json"
smallform_0646_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0011.jpg/info.json"
smallform_0646_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0012.jpg/info.json"
smallform_0646_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0013.jpg/info.json"
smallform_0646_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0014.jpg/info.json"
smallform_0646_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0015.jpg/info.json"
smallform_0646_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0016.jpg/info.json"
smallform_0646_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0017.jpg/info.json"
smallform_0646_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0018.jpg/info.json"
smallform_0646_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0019.jpg/info.json"
smallform_0646_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0020.jpg/info.json"
smallform_0646_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0021.jpg/info.json"
smallform_0646_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0022.jpg/info.json"
smallform_0646_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0023.jpg/info.json"
smallform_0646_024 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0024.jpg/info.json"
smallform_0646_025 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0025.jpg/info.json"
smallform_0646_026 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0026.jpg/info.json"
smallform_0646_027 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0027.jpg/info.json"
smallform_0646_028 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0028.jpg/info.json"
smallform_0646_029 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0029.jpg/info.json"
smallform_0646_030 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0030.jpg/info.json"
smallform_0646_031 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0646_0031.jpg/info.json"
