mf_id = "smallform_0352.json"
mf_lang = "en"
mf_label = "9. Die menschliche Landschaft [Textzeuge a]"

[mf_data]
"smallform_0352_0043.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0043.jpg/info.json"
"smallform_0352_0044.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0044.jpg/info.json"
"smallform_0352_0045.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0045.jpg/info.json"
"smallform_0352_0046.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0046.jpg/info.json"
"smallform_0352_0047.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0047.jpg/info.json"
"smallform_0352_0048.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0048.jpg/info.json"
"smallform_0352_0049.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0049.jpg/info.json"
"smallform_0352_0050.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0050.jpg/info.json"
"smallform_0352_0051.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0051.jpg/info.json"
