mf_id = "smallform_0255.json"
mf_lang = "en"
mf_label = "Besinnung auf Thomas Jefferson [Textzeuge a]"

[mf_data]
"smallform_0255_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0255_0001.jpg/info.json"
"smallform_0255_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0255_0002.jpg/info.json"
"smallform_0255_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0255_0003.jpg/info.json"
"smallform_0255_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0255_0004.jpg/info.json"
"smallform_0255_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0255_0005.jpg/info.json"
"smallform_0255_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0255_0006.jpg/info.json"
