mf_id = "smallform_0051.json"
mf_lang = "en"
mf_label = "Die neue landwirtschaftliche Hochschule in Ankara"

[mf_data]
smallform_0051_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0051_0001.jpg/info.json"
smallform_0051_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0051_0002.jpg/info.json"
smallform_0051_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0051_0003.jpg/info.json"
