mf_id = "smallform_0354.json"
mf_lang = "en"
mf_label = "Bamiyan, oder die schönen Erinnerungen (Dez. 1939)"

[mf_data]
smallform_0354_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0354_0001.jpg/info.json"
smallform_0354_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0354_0002.jpg/info.json"
smallform_0354_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0354_0003.jpg/info.json"
smallform_0354_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0354_0004.jpg/info.json"
smallform_0354_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0354_0005.jpg/info.json"
smallform_0354_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0354_0006.jpg/info.json"
