mf_id = "smallform_0687.json"
mf_lang = "en"
mf_label = "*Aktuelles aus Afghanistan [Textzeuge b]"

[mf_data]
smallform_0687_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0687_0001.jpg/info.json"
smallform_0687_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0687_0002.jpg/info.json"
smallform_0687_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0687_0003.jpg/info.json"
