mf_id = "smallform_0320.json"
mf_lang = "en"
mf_label = "Die Steppe"

[mf_data]
smallform_0320_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0320_0001.jpg/info.json"
smallform_0320_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0320_0002.jpg/info.json"
smallform_0320_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0320_0003.jpg/info.json"
smallform_0320_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0320_0004.jpg/info.json"
