mf_id = "smallform_0181.json"
mf_lang = "en"
mf_label = "Art : Kunst in Amerika"

[mf_data]
"smallform_0181_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0181_0001.jpg/info.json"
"smallform_0181_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0181_0002.jpg/info.json"
"smallform_0181_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0181_0003.jpg/info.json"
"smallform_0181_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0181_0004.jpg/info.json"
"smallform_0181_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0181_0005.jpg/info.json"
