mf_id = "smallform_0292.json"
mf_lang = "en"
mf_label = "\"Oesterreich gründlich verändert\" [Textzeuge a - Deutsch]"

[mf_data]
smallform_0292_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0292_0001.jpg/info.json"
smallform_0292_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0292_0002.jpg/info.json"
smallform_0292_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0292_0003.jpg/info.json"
smallform_0292_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0292_0004.jpg/info.json"
smallform_0292_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0292_0005.jpg/info.json"
