mf_id = "smallform_0140.json"
mf_lang = "en"
mf_label = "Sehr viel Geduld ... "

[mf_data]
smallform_0140_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0001.jpg/info.json"
smallform_0140_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0002.jpg/info.json"
smallform_0140_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0003.jpg/info.json"
smallform_0140_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0004.jpg/info.json"
smallform_0140_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0005.jpg/info.json"
smallform_0140_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0006.jpg/info.json"
smallform_0140_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0007.jpg/info.json"
smallform_0140_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0008.jpg/info.json"
smallform_0140_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0009.jpg/info.json"
smallform_0140_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0010.jpg/info.json"
smallform_0140_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0011.jpg/info.json"
smallform_0140_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0012.jpg/info.json"
smallform_0140_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0013.jpg/info.json"
smallform_0140_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0014.jpg/info.json"
smallform_0140_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0015.jpg/info.json"
smallform_0140_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0140_0016.jpg/info.json"
