mf_id = "smallform_0410.json"
mf_lang = "en"
mf_label = "Nach Peshawar ..."

[mf_data]
smallform_0410_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0410_0001.jpg/info.json"
smallform_0410_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0410_0002.jpg/info.json"
smallform_0410_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0410_0003.jpg/info.json"
smallform_0410_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0410_0004.jpg/info.json"
