mf_id = "smallform_0008.json"
mf_lang = "en"
mf_label = "[Ena Bernstein = eine Frau zu sehen]"

[mf_data]
smallform_0008_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0001.jpg/info.json"
smallform_0008_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0002.jpg/info.json"
smallform_0008_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0003.jpg/info.json"
smallform_0008_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0004.jpg/info.json"
smallform_0008_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0005.jpg/info.json"
smallform_0008_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0006.jpg/info.json"
smallform_0008_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0007.jpg/info.json"
smallform_0008_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0008.jpg/info.json"
smallform_0008_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0009.jpg/info.json"
smallform_0008_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0010.jpg/info.json"
smallform_0008_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0011.jpg/info.json"
smallform_0008_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0012.jpg/info.json"
smallform_0008_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0013.jpg/info.json"
smallform_0008_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0014.jpg/info.json"
smallform_0008_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0015.jpg/info.json"
smallform_0008_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0016.jpg/info.json"
smallform_0008_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0017.jpg/info.json"
smallform_0008_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0018.jpg/info.json"
smallform_0008_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0019.jpg/info.json"
smallform_0008_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0020.jpg/info.json"
smallform_0008_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0021.jpg/info.json"
smallform_0008_022 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0022.jpg/info.json"
smallform_0008_023 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0023.jpg/info.json"
smallform_0008_024 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0024.jpg/info.json"
smallform_0008_025 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0025.jpg/info.json"
smallform_0008_026 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0026.jpg/info.json"
smallform_0008_027 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0027.jpg/info.json"
smallform_0008_028 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0028.jpg/info.json"
smallform_0008_029 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0029.jpg/info.json"
smallform_0008_030 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0030.jpg/info.json"
smallform_0008_031 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0031.jpg/info.json"
smallform_0008_032 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0032.jpg/info.json"
smallform_0008_033 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0033.jpg/info.json"
smallform_0008_034 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0034.jpg/info.json"
smallform_0008_035 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0035.jpg/info.json"
smallform_0008_036 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0036.jpg/info.json"
smallform_0008_037 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0037.jpg/info.json"
smallform_0008_038 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0038.jpg/info.json"
smallform_0008_039 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0039.jpg/info.json"
smallform_0008_040 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0040.jpg/info.json"
smallform_0008_041 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0041.jpg/info.json"
smallform_0008_042 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0042.jpg/info.json"
smallform_0008_043 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0043.jpg/info.json"
smallform_0008_044 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0044.jpg/info.json"
smallform_0008_045 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0045.jpg/info.json"
smallform_0008_046 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0046.jpg/info.json"
smallform_0008_047 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0047.jpg/info.json"
smallform_0008_048 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0048.jpg/info.json"
smallform_0008_049 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0049.jpg/info.json"
smallform_0008_050 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0050.jpg/info.json"
smallform_0008_051 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0051.jpg/info.json"
smallform_0008_052 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0052.jpg/info.json"
smallform_0008_053 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0053.jpg/info.json"
smallform_0008_054 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0054.jpg/info.json"
smallform_0008_055 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0055.jpg/info.json"
smallform_0008_056 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0056.jpg/info.json"
smallform_0008_057 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0057.jpg/info.json"
smallform_0008_058 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0058.jpg/info.json"
smallform_0008_059 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0059.jpg/info.json"
smallform_0008_060 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0060.jpg/info.json"
smallform_0008_061 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0008_0061.jpg/info.json"
