mf_id = "smallform_0162.json"
mf_lang = "en"
mf_label = "Besuch bei einem Perser auf dem Land"

[mf_data]
"smallform_0162_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0001.jpg/info.json"
"smallform_0162_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0002.jpg/info.json"
"smallform_0162_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0003.jpg/info.json"
"smallform_0162_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0004.jpg/info.json"
"smallform_0162_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0005.jpg/info.json"
"smallform_0162_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0006.jpg/info.json"
"smallform_0162_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0007.jpg/info.json"
"smallform_0162_0008.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0008.jpg/info.json"
"smallform_0162_0009.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0009.jpg/info.json"
"smallform_0162_0010.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0010.jpg/info.json"
"smallform_0162_0011.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0011.jpg/info.json"
"smallform_0162_0012.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0162_0012.jpg/info.json"
