mf_id = "smallform_0645.json"
mf_lang = "en"
mf_label = "Pariser Novelle [Textzeuge c]"

[mf_data]
smallform_0645_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0001.jpg/info.json"
smallform_0645_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0002.jpg/info.json"
smallform_0645_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0003.jpg/info.json"
smallform_0645_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0004.jpg/info.json"
smallform_0645_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0005.jpg/info.json"
smallform_0645_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0006.jpg/info.json"
smallform_0645_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0007.jpg/info.json"
smallform_0645_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0008.jpg/info.json"
smallform_0645_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0009.jpg/info.json"
smallform_0645_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0010.jpg/info.json"
smallform_0645_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0011.jpg/info.json"
smallform_0645_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0012.jpg/info.json"
smallform_0645_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0013.jpg/info.json"
smallform_0645_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0014.jpg/info.json"
smallform_0645_015 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0015.jpg/info.json"
smallform_0645_016 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0016.jpg/info.json"
smallform_0645_017 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0017.jpg/info.json"
smallform_0645_018 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0018.jpg/info.json"
smallform_0645_019 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0019.jpg/info.json"
smallform_0645_020 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0020.jpg/info.json"
smallform_0645_021 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0645_0021.jpg/info.json"
