mf_id = "smallform_0712.json"
mf_lang = "en"
mf_label = "Wie lebt ... Aline Bryant, Textilarbeiterin im amerikanischen Südstaat Tennessee"

[mf_data]
smallform_0712_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0712_0001.jpg/info.json"
smallform_0712_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0712_0002.jpg/info.json"
smallform_0712_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0712_0003.jpg/info.json"
smallform_0712_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0712_0004.jpg/info.json"
smallform_0712_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0712_0005.jpg/info.json"
smallform_0712_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0712_0006.jpg/info.json"
smallform_0712_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0712_0007.jpg/info.json"
smallform_0712_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0712_0008.jpg/info.json"
