mf_id = "smallform_0049.json"
mf_lang = "en"
mf_label = "Ausflug nach Anatolien"

[mf_data]
"smallform_0049_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0049_0001.jpg/info.json"
"smallform_0049_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0049_0002.jpg/info.json"
"smallform_0049_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0049_0003.jpg/info.json"
