mf_id = "smallform_0352.json"
mf_lang = "en"
mf_label = "9. Die menschliche Landschaft [Textzeuge a]"

[mf_data]
smallform_0352_043 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0043.jpg/info.json"
smallform_0352_044 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0044.jpg/info.json"
smallform_0352_045 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0045.jpg/info.json"
smallform_0352_046 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0046.jpg/info.json"
smallform_0352_047 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0047.jpg/info.json"
smallform_0352_048 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0048.jpg/info.json"
smallform_0352_049 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0049.jpg/info.json"
smallform_0352_050 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0050.jpg/info.json"
smallform_0352_051 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0352_0051.jpg/info.json"
