mf_id = "smallform_0702.json"
mf_lang = "en"
mf_label = "Herr! Das Namenlose (März/ April 1941) [Textzeuge d]"

[mf_data]
smallform_0702_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0702_0001.jpg/info.json"
smallform_0702_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0702_0002.jpg/info.json"
smallform_0702_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0702_0003.jpg/info.json"
smallform_0702_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0702_0004.jpg/info.json"
smallform_0702_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0702_0005.jpg/info.json"
smallform_0702_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0702_0006.jpg/info.json"
smallform_0702_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0702_0007.jpg/info.json"
smallform_0702_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0702_0008.jpg/info.json"
