mf_id = "smallform_0726.json"
mf_lang = "en"
mf_label = "Die Insel"

[mf_data]
"smallform_0726_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0726_0001.jpg/info.json"
"smallform_0726_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0726_0002.jpg/info.json"
"smallform_0726_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0726_0003.jpg/info.json"
