mf_id = "smallform_0761.json"
mf_lang = "en"
mf_label = "[Inhaltsverzeichnis Die vierzig Säulen der Erinnerung] [Textzeuge c - Fotokopie]"

[mf_data]
smallform_0761_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0761_0001.jpg/info.json"
