mf_id = "smallform_0704.json"
mf_lang = "en"
mf_label = "Kongo-Ufer, I-V (1941) [Textzeuge c]"

[mf_data]
"smallform_0704_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0704_0001.jpg/info.json"
"smallform_0704_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0704_0002.jpg/info.json"
"smallform_0704_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0704_0003.jpg/info.json"
"smallform_0704_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0704_0004.jpg/info.json"
"smallform_0704_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0704_0005.jpg/info.json"
"smallform_0704_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0704_0006.jpg/info.json"
"smallform_0704_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0704_0007.jpg/info.json"
