mf_id = "smallform_0443.json"
mf_lang = "en"
mf_label = "Carson McCullers "

[mf_data]
smallform_0443_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0443_0001.jpg/info.json"
smallform_0443_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0443_0002.jpg/info.json"
