mf_id = "smallform_0779.json"
mf_lang = "en"
mf_label = "Marokkanische Erntezeit"

[mf_data]
smallform_0779_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0779_001.jpg/info.json"
smallform_0779_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0779_002.jpg/info.json"
smallform_0779_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0779_003.jpg/info.json"
smallform_0779_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0779_004.jpg/info.json"
smallform_0779_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0779_005.jpg/info.json"
