mf_id = "smallform_0462.json"
mf_lang = "en"
mf_label = "Turkish delight and dilemna"

[mf_data]
"smallform_0462_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0462_0001.jpg/info.json"
"smallform_0462_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0462_0002.jpg/info.json"
"smallform_0462_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0462_0003.jpg/info.json"
"smallform_0462_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0462_0004.jpg/info.json"
"smallform_0462_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0462_0005.jpg/info.json"
"smallform_0462_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0462_0006.jpg/info.json"
