mf_id = "smallform_0770.json"
mf_lang = "en"
mf_label = "9. Die menschliche Landschaft [Textzeuge c - Fotokopie]"

[mf_data]
"smallform_0770_0026.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0770_0026.jpg/info.json"
"smallform_0770_0027.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0770_0027.jpg/info.json"
"smallform_0770_0028.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0770_0028.jpg/info.json"
"smallform_0770_0029.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0770_0029.jpg/info.json"
"smallform_0770_0030.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0770_0030.jpg/info.json"
