mf_id = "smallform_0083.json"
mf_lang = "en"
mf_label = "Nachtflug über die Wüste"

[mf_data]
smallform_0083_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0083_0001.jpg/info.json"
smallform_0083_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0083_0002.jpg/info.json"
smallform_0083_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0083_0003.jpg/info.json"
smallform_0083_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0083_0004.jpg/info.json"
smallform_0083_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0083_0005.jpg/info.json"
