mf_id = "smallform_0218.json"
mf_lang = "en"
mf_label = "Von Gustav Adolf bis zu Jwar Kreugher"

[mf_data]
"smallform_0218_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0218_0001.jpg/info.json"
"smallform_0218_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0218_0002.jpg/info.json"
