mf_id = "smallform_0460.json"
mf_lang = "en"
mf_label = "Amerikanische Ereignisse: 3. Oberst Lindbergh auf der politischen Bühne"

[mf_data]
"smallform_0460_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0460_0001.jpg/info.json"
"smallform_0460_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0460_0002.jpg/info.json"
"smallform_0460_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0460_0003.jpg/info.json"
"smallform_0460_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0460_0004.jpg/info.json"
