mf_id = "smallform_0444.json"
mf_lang = "en"
mf_label = "Amerikanisches Tagebuch. I. Die Weltausstellung [Textzeuge a]"

[mf_data]
"smallform_0444_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0444_0001.jpg/info.json"
"smallform_0444_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0444_0002.jpg/info.json"
