mf_id = "smallform_0754.json"
mf_lang = "en"
mf_label = "8. Der Aufbruch, die nie bereute Stunde [Textzeuge b - Abschrift]"

[mf_data]
"smallform_0754_0016.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0754_0016.jpg/info.json"
"smallform_0754_0017.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0754_0017.jpg/info.json"
