mf_id = "smallform_0750.json"
mf_lang = "en"
mf_label = "4. Der persische Gartenteich [Textzeuge b - Abschrift]"

[mf_data]
"smallform_0750_0009.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0750_0009.jpg/info.json"
