mf_id = "smallform_0031.json"
mf_lang = "en"
mf_label = "Der Fluss [Textzeuge a]"

[mf_data]
smallform_0031_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0031_0001.jpg/info.json"
smallform_0031_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0031_0002.jpg/info.json"
smallform_0031_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0031_0003.jpg/info.json"
smallform_0031_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0031_0004.jpg/info.json"
smallform_0031_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0031_0005.jpg/info.json"
smallform_0031_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0031_0006.jpg/info.json"
smallform_0031_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0031_0007.jpg/info.json"
smallform_0031_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0031_0008.jpg/info.json"
smallform_0031_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0031_0009.jpg/info.json"
smallform_0031_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0031_0010.jpg/info.json"
