mf_id = "smallform_0778.json"
mf_lang = "en"
mf_label = "Die zärtlichen Wege, unsere Einsamkeit"

[mf_data]
smallform_0778_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0778_001.jpg/info.json"
smallform_0778_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0778_002.jpg/info.json"
smallform_0778_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0778_003.jpg/info.json"
smallform_0778_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0778_004.jpg/info.json"
smallform_0778_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0778_005.jpg/info.json"
smallform_0778_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0778_006.jpg/info.json"
smallform_0778_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0778_007.jpg/info.json"
smallform_0778_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0778_008.jpg/info.json"
smallform_0778_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0778_009.jpg/info.json"
