mf_id = "smallform_0765.json"
mf_lang = "en"
mf_label = "4. Der persische Gartenteich [Textzeuge c - Fotokopie]"

[mf_data]
smallform_0765_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0765_0012.jpg/info.json"
