mf_id = "smallform_0539.json"
mf_lang = "en"
mf_label = "Herr! Das Namenlose (März/ April 1941) [Textzeuge a]"

[mf_data]
smallform_0539_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0539_0001.jpg/info.json"
smallform_0539_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0539_0002.jpg/info.json"
smallform_0539_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0539_0003.jpg/info.json"
smallform_0539_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0539_0004.jpg/info.json"
smallform_0539_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0539_0005.jpg/info.json"
smallform_0539_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0539_0006.jpg/info.json"
smallform_0539_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0539_0007.jpg/info.json"
smallform_0539_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0539_0008.jpg/info.json"
