mf_id = "smallform_0720.json"
mf_lang = "en"
mf_label = "Jahreswechsel in U.S.A.: 3. Januar-Sensationen [Textzeuge b]"

[mf_data]
smallform_0720_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0720_0001.jpg/info.json"
smallform_0720_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0720_0002.jpg/info.json"
smallform_0720_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0720_0003.jpg/info.json"
