mf_id = "smallform_0347.json"
mf_lang = "en"
mf_label = "4. Der persische Gartenteich [Textzeuge a]"

[mf_data]
"smallform_0347_0019.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0347_0019.jpg/info.json"
