mf_id = "smallform_0741.json"
mf_lang = "en"
mf_label = "Nantucket Island, am ersten August [Textzeuge b]\n"

[mf_data]
"smallform_0741_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0741_0004.jpg/info.json"
"smallform_0741_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0741_0005.jpg/info.json"
"smallform_0741_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0741_0006.jpg/info.json"
