mf_id = "smallform_0683.json"
mf_lang = "en"
mf_label = "Zwischen den Ländern [Textzeuge b]"

[mf_data]
smallform_0683_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0683_0001.jpg/info.json"
smallform_0683_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0683_0002.jpg/info.json"
smallform_0683_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0683_0003.jpg/info.json"
smallform_0683_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0683_0004.jpg/info.json"
smallform_0683_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0683_0005.jpg/info.json"
smallform_0683_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0683_0006.jpg/info.json"
