mf_id = "smallform_0582.json"
mf_lang = "en"
mf_label = "Neues Leben in Marokko."

[mf_data]
smallform_0582_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0582_0001.jpg/info.json"
smallform_0582_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0582_0002.jpg/info.json"
smallform_0582_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0582_0003.jpg/info.json"
smallform_0582_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0582_0004.jpg/info.json"
