mf_id = "smallform_0691.json"
mf_lang = "en"
mf_label = "Amerikanisches Tagebuch. I. Die Weltausstellung [Textzeuge b]"

[mf_data]
smallform_0691_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0691_0001.jpg/info.json"
smallform_0691_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0691_0002.jpg/info.json"
