mf_id = "smallform_0306.json"
mf_lang = "en"
mf_label = "Neben dem Orient-Express (über Balkangrenzen) [Textzeuge a]"

[mf_data]
smallform_0306_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0306_0001.jpg/info.json"
smallform_0306_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0306_0002.jpg/info.json"
smallform_0306_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0306_0003.jpg/info.json"
smallform_0306_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0306_0004.jpg/info.json"
