mf_id = "smallform_0054.json"
mf_lang = "en"
mf_label = "Konya (Tagebuch. - 3. Ex.)"

[mf_data]
"smallform_0054_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0054_0001.jpg/info.json"
"smallform_0054_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0054_0002.jpg/info.json"
