mf_id = "smallform_0322.json"
mf_lang = "en"
mf_label = "Mobilisiert in Kabul ..."

[mf_data]
"smallform_0322_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0322_0001.jpg/info.json"
"smallform_0322_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0322_0002.jpg/info.json"
"smallform_0322_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0322_0003.jpg/info.json"
"smallform_0322_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0322_0004.jpg/info.json"
"smallform_0322_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0322_0005.jpg/info.json"
"smallform_0322_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0322_0006.jpg/info.json"
"smallform_0322_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0322_0007.jpg/info.json"
"smallform_0322_0008.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0322_0008.jpg/info.json"
