mf_id = "smallform_0561.json"
mf_lang = "en"
mf_label = "Vandalengeschichten"

[mf_data]
smallform_0561_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0561_0001.jpg/info.json"
smallform_0561_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0561_0002.jpg/info.json"
smallform_0561_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0561_0003.jpg/info.json"
smallform_0561_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0561_0004.jpg/info.json"
smallform_0561_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0561_0005.jpg/info.json"
