mf_id = "smallform_0377.json"
mf_lang = "en"
mf_label = "«Gastfreundliches Afghanistan» [Textzeuge a]\n\n\n"

[mf_data]
"smallform_0377_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0377_0001.jpg/info.json"
"smallform_0377_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0377_0002.jpg/info.json"
"smallform_0377_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0377_0003.jpg/info.json"
"smallform_0377_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0377_0004.jpg/info.json"
"smallform_0377_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0377_0005.jpg/info.json"
"smallform_0377_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0377_0006.jpg/info.json"
