mf_id = "smallform_0738.json"
mf_lang = "en"
mf_label = "Dargawskaja: ein Kaukasus-Dorf"

[mf_data]
"smallform_0738_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0738_0001.jpg/info.json"
