mf_id = "smallform_0350.json"
mf_lang = "en"
mf_label = "7. Der Winterabend [Textzeuge a]"

[mf_data]
smallform_0350_030 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0350_0030.jpg/info.json"
smallform_0350_031 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0350_0031.jpg/info.json"
smallform_0350_032 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0350_0032.jpg/info.json"
smallform_0350_033 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0350_0033.jpg/info.json"
smallform_0350_034 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0350_0034.jpg/info.json"
smallform_0350_035 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0350_0035.jpg/info.json"
