mf_id = "smallform_0351.json"
mf_lang = "en"
mf_label = "8. Der Aufbruch, die nie bereute Stunde [Textzeuge a]"

[mf_data]
"smallform_0351_0036.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0351_0036.jpg/info.json"
"smallform_0351_0037.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0351_0037.jpg/info.json"
"smallform_0351_0038.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0351_0038.jpg/info.json"
"smallform_0351_0039.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0351_0039.jpg/info.json"
"smallform_0351_0040.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0351_0040.jpg/info.json"
"smallform_0351_0041.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0351_0041.jpg/info.json"
"smallform_0351_0042.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0351_0042.jpg/info.json"
