mf_id = "smallform_0134.json"
mf_lang = "en"
mf_label = "Verklärtes Europa "

[mf_data]
smallform_0134_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0134_0001.jpg/info.json"
smallform_0134_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0134_0002.jpg/info.json"
smallform_0134_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0134_0003.jpg/info.json"
smallform_0134_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0134_0004.jpg/info.json"
smallform_0134_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0134_0005.jpg/info.json"
smallform_0134_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0134_0006.jpg/info.json"
