mf_id = "smallform_0675.json"
mf_lang = "en"
mf_label = "Das Oxus-Ufer (20.11.1939) [Textzeuge b]"

[mf_data]
"smallform_0675_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0675_0001.jpg/info.json"
"smallform_0675_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0675_0002.jpg/info.json"
"smallform_0675_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0675_0003.jpg/info.json"
"smallform_0675_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0675_0004.jpg/info.json"
"smallform_0675_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0675_0005.jpg/info.json"
"smallform_0675_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0675_0006.jpg/info.json"
