mf_id = "smallform_0473.json"
mf_lang = "en"
mf_label = "Amerikanische Ereignisse: 4. Umstellung auf Rüstungsindustrie"

[mf_data]
"smallform_0473_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0473_0001.jpg/info.json"
"smallform_0473_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0473_0002.jpg/info.json"
"smallform_0473_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0473_0003.jpg/info.json"
"smallform_0473_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0473_0004.jpg/info.json"
