mf_id = "smallform_0521.json"
mf_lang = "en"
mf_label = "Afghanistan"

[mf_data]
"smallform_0521_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0001.jpg/info.json"
"smallform_0521_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0002.jpg/info.json"
"smallform_0521_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0003.jpg/info.json"
"smallform_0521_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0004.jpg/info.json"
"smallform_0521_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0005.jpg/info.json"
"smallform_0521_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0006.jpg/info.json"
"smallform_0521_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0007.jpg/info.json"
"smallform_0521_0008.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0008.jpg/info.json"
"smallform_0521_0009.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0009.jpg/info.json"
"smallform_0521_0010.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0010.jpg/info.json"
"smallform_0521_0011.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0011.jpg/info.json"
"smallform_0521_0012.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0012.jpg/info.json"
"smallform_0521_0013.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0013.jpg/info.json"
"smallform_0521_0014.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0014.jpg/info.json"
"smallform_0521_0015.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0015.jpg/info.json"
"smallform_0521_0016.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0521_0016.jpg/info.json"
