mf_id = "smallform_0768.json"
mf_lang = "en"
mf_label = "7. Der Winterabend  [Textzeuge c - Fotokopie]"

[mf_data]
"smallform_0768_0019.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0768_0019.jpg/info.json"
"smallform_0768_0020.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0768_0020.jpg/info.json"
"smallform_0768_0021.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0768_0021.jpg/info.json"
