mf_id = "smallform_0449.json"
mf_lang = "en"
mf_label = "Die Schweiz - das Land, das nicht zum Schuss kam (Ende Juli 1940)"

[mf_data]
smallform_0449_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0449_0001.jpg/info.json"
smallform_0449_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0449_0002.jpg/info.json"
smallform_0449_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0449_0003.jpg/info.json"
smallform_0449_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0449_0004.jpg/info.json"
smallform_0449_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0449_0005.jpg/info.json"
smallform_0449_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0449_0006.jpg/info.json"
smallform_0449_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0449_0007.jpg/info.json"
smallform_0449_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0449_0008.jpg/info.json"
smallform_0449_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0449_0009.jpg/info.json"
smallform_0449_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0449_0010.jpg/info.json"
smallform_0449_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0449_0011.jpg/info.json"
