mf_id = "smallform_0504.json"
mf_lang = "en"
mf_label = "Rückkehr nach Lissabon"

[mf_data]
"smallform_0504_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0504_0001.jpg/info.json"
"smallform_0504_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0504_0002.jpg/info.json"
