mf_id = "smallform_0728.json"
mf_lang = "en"
mf_label = "Nantucket Island, am ersten August [Textzeuge a]"

[mf_data]
"smallform_0728_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0728_0001.jpg/info.json"
"smallform_0728_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0728_0002.jpg/info.json"
"smallform_0728_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0728_0003.jpg/info.json"
