mf_id = "smallform_0686.json"
mf_lang = "en"
mf_label = "«Gastfreundliches Afghanistan» [Textzeuge c]\n\n\n"

[mf_data]
smallform_0686_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0686_0001.jpg/info.json"
smallform_0686_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0686_0002.jpg/info.json"
smallform_0686_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0686_0003.jpg/info.json"
smallform_0686_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0686_0004.jpg/info.json"
smallform_0686_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0686_0005.jpg/info.json"
smallform_0686_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0686_0006.jpg/info.json"
