mf_id = "smallform_0256.json"
mf_lang = "en"
mf_label = "Kinder ohne Uniform"

[mf_data]
smallform_0256_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0256_0001.jpg/info.json"
smallform_0256_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0256_0002.jpg/info.json"
smallform_0256_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0256_0003.jpg/info.json"
