mf_id = "smallform_0263.json"
mf_lang = "en"
mf_label = "Cincinnati : eine normale amerikanische Stadt"

[mf_data]
"smallform_0263_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0263_0001.jpg/info.json"
"smallform_0263_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0263_0002.jpg/info.json"
"smallform_0263_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0263_0003.jpg/info.json"
