mf_id = "smallform_0204.json"
mf_lang = "en"
mf_label = "Aufnahmen von Annemarie Clarac-Schwarzenbach"

[mf_data]
"smallform_0204_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0204_0001.jpg/info.json"
