mf_id = "smallform_0716.json"
mf_lang = "en"
mf_label = "Jahreswechsel in U.S.A.: 1. Der Maginot-Ozean [Textzeuge a]"

[mf_data]
smallform_0716_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0716_0001.jpg/info.json"
smallform_0716_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0716_0002.jpg/info.json"
smallform_0716_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0716_0003.jpg/info.json"
