mf_id = "smallform_0668.json"
mf_lang = "en"
mf_label = "\"Oesterreich gründlich verändert\" [Textzeuge b - Französisch]"

[mf_data]
"smallform_0668_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0668_0001.jpg/info.json"
"smallform_0668_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0668_0002.jpg/info.json"
"smallform_0668_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0668_0003.jpg/info.json"
"smallform_0668_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0668_0004.jpg/info.json"
"smallform_0668_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0668_0005.jpg/info.json"
