mf_id = "smallform_0006.json"
mf_lang = "en"
mf_label = "Erik [Textzeuge a]"

[mf_data]
"smallform_0006_0001.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0001.jpg/info.json"
"smallform_0006_0002.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0002.jpg/info.json"
"smallform_0006_0003.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0003.jpg/info.json"
"smallform_0006_0004.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0004.jpg/info.json"
"smallform_0006_0005.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0005.jpg/info.json"
"smallform_0006_0006.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0006.jpg/info.json"
"smallform_0006_0007.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0007.jpg/info.json"
"smallform_0006_0008.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0008.jpg/info.json"
"smallform_0006_0009.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0009.jpg/info.json"
"smallform_0006_0010.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0010.jpg/info.json"
"smallform_0006_0011.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0011.jpg/info.json"
"smallform_0006_0012.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0012.jpg/info.json"
"smallform_0006_0013.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0013.jpg/info.json"
"smallform_0006_0014.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0014.jpg/info.json"
"smallform_0006_0015.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0015.jpg/info.json"
"smallform_0006_0016.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0016.jpg/info.json"
"smallform_0006_0017.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0017.jpg/info.json"
"smallform_0006_0018.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0018.jpg/info.json"
"smallform_0006_0019.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0019.jpg/info.json"
"smallform_0006_0020.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0020.jpg/info.json"
"smallform_0006_0021.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0021.jpg/info.json"
"smallform_0006_0022.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0022.jpg/info.json"
"smallform_0006_0023.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0023.jpg/info.json"
"smallform_0006_0024.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0024.jpg/info.json"
"smallform_0006_0025.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0025.jpg/info.json"
"smallform_0006_0026.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0026.jpg/info.json"
"smallform_0006_0027.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0027.jpg/info.json"
"smallform_0006_0028.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0028.jpg/info.json"
"smallform_0006_0029.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0029.jpg/info.json"
"smallform_0006_0030.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0030.jpg/info.json"
"smallform_0006_0031.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0031.jpg/info.json"
"smallform_0006_0032.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0032.jpg/info.json"
"smallform_0006_0033.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0033.jpg/info.json"
"smallform_0006_0034.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0034.jpg/info.json"
"smallform_0006_0035.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0035.jpg/info.json"
"smallform_0006_0036.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0036.jpg/info.json"
"smallform_0006_0037.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0037.jpg/info.json"
"smallform_0006_0038.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0038.jpg/info.json"
"smallform_0006_0039.jpg" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0006_0039.jpg/info.json"
