mf_id = "smallform_0064.json"
mf_lang = "en"
mf_label = "[Thema: Die Beduinen in Syrien]"

[mf_data]
smallform_0064_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0064_0001.jpg/info.json"
smallform_0064_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0064_0002.jpg/info.json"
smallform_0064_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0064_0003.jpg/info.json"
smallform_0064_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0064_0004.jpg/info.json"
smallform_0064_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0064_0005.jpg/info.json"
