mf_id = "smallform_0713.json"
mf_lang = "en"
mf_label = "[Tagebuch] Thema: TVA (Tennessee Valley Authority)"

[mf_data]
smallform_0713_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0713_0001.jpg/info.json"
smallform_0713_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0713_0002.jpg/info.json"
smallform_0713_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0713_0003.jpg/info.json"
smallform_0713_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0713_0004.jpg/info.json"
smallform_0713_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0713_0005.jpg/info.json"
smallform_0713_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0713_0006.jpg/info.json"
smallform_0713_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0713_0007.jpg/info.json"
smallform_0713_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0713_0008.jpg/info.json"
smallform_0713_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0713_0009.jpg/info.json"
