mf_id = "smallform_0026.json"
mf_lang = "en"
mf_label = "Der Hut : eine Episode aus dem Leben der Familie Schwarzenbach auf Bocken"

[mf_data]
smallform_0026_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0001.jpg/info.json"
smallform_0026_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0002.jpg/info.json"
smallform_0026_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0003.jpg/info.json"
smallform_0026_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0004.jpg/info.json"
smallform_0026_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0005.jpg/info.json"
smallform_0026_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0006.jpg/info.json"
smallform_0026_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0007.jpg/info.json"
smallform_0026_008 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0008.jpg/info.json"
smallform_0026_009 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0009.jpg/info.json"
smallform_0026_010 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0010.jpg/info.json"
smallform_0026_011 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0011.jpg/info.json"
smallform_0026_012 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0012.jpg/info.json"
smallform_0026_013 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0013.jpg/info.json"
smallform_0026_014 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0026_0014.jpg/info.json"
