mf_id = "smallform_0075.json"
mf_lang = "en"
mf_label = "Syrische Weihnachtstage"

[mf_data]
smallform_0075_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0075_0001.jpg/info.json"
smallform_0075_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0075_0002.jpg/info.json"
smallform_0075_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0075_0003.jpg/info.json"
smallform_0075_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0075_0004.jpg/info.json"
