mf_id = "smallform_0742.json"
mf_lang = "en"
mf_label = "Ruth [Textzeuge a]"

[mf_data]
smallform_0742_001 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0742_0001.jpg/info.json"
smallform_0742_002 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0742_0002.jpg/info.json"
smallform_0742_003 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0742_0003.jpg/info.json"
smallform_0742_004 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0742_0004.jpg/info.json"
smallform_0742_005 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0742_0005.jpg/info.json"
smallform_0742_006 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0742_0006.jpg/info.json"
smallform_0742_007 = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0742_0007.jpg/info.json"
